### ISSUE TITLE
Activate payment when order status is set to a specific status

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#10]

**Comment by andyjohansson** [comment]
Tested now, see this test protocol. https://docs.google.com/spreadsheets/d/1iJjPxB_XYUiIf_eSG81oZ29X-jsF9G0wS2q3KZ-mUOE/edit?usp=sharing

**Comment by Boxedsolutions** [comment]
Should show notification on error or already activated status

**Comment by andyjohansson** [comment]
Passed test.
