### ISSUE TITLE
Clarify that the invoice fee is (ex. moms) in admin panel

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#101]
![skarmavbild 2015-02-17 kl 14 41 04](https://cloud.githubusercontent.com/assets/4968755/6229023/08c4c5ae-b6b3-11e4-85dd-27502c96aaa9.png)

**Comment by Boxedsolutions** [comment]
wrong reference.

**Comment by Boxedsolutions** [comment]
Please give me the english version and Swedish and I will correct that

**Comment by andyjohansson** [comment]
Invoice Fee ex. VAT (kr)
Fakturaavg. ex. moms (kr)

**Comment by andyjohansson** [comment]
Invoice Fee ex. tax (kr)
Fakturaavg. ex. moms (kr)

This is more correct to PrestaShop standards.

**Comment by andyjohansson** [comment]
All of these should have a space before (kr). See attached image. Also for english, see other attached image.
![skarmavbild 2015-03-03 kl 10 14 59](https://cloud.githubusercontent.com/assets/4968755/6459401/81882ea0-c18e-11e4-88fe-c5a007a6f9fa.png)
![skarmavbild 2015-03-03 kl 10 16 18](https://cloud.githubusercontent.com/assets/4968755/6459402/8189ac44-c18e-11e4-98d0-6abb46edb244.png)

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
Ehm, no? Looks a vit weird now?
![skarmavbild 2015-03-03 kl 14 09 52](https://cloud.githubusercontent.com/assets/4968755/6463045/fcd9803e-c1ae-11e4-8463-654042df1c79.png)

**Comment by Boxedsolutions** [comment]
Ahh you mean the space should be before the parentheses?

**Comment by Boxedsolutions** [comment]
Should be fixed
