### ISSUE TITLE
The label is to tight to the radio button on Invoice Activation on Orderstatus

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#103]
![skarmavbild 2015-02-17 kl 14 56 32](https://cloud.githubusercontent.com/assets/4968755/6229173/39c54bf4-b6b5-11e4-925e-fa1e80a5c7ca.png)

**Comment by andyjohansson** [comment]
Can't see any CSS differences when I look at it.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
Fixed.
