### ISSUE TITLE
Add compatibility with "One Page Checkout PS"

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#105]
Also add compatibility with get adress and this checkout,

http://www.presteamshop.com/en/modules-prestashop/one-page-checkout-prestashop.html

**Comment by Boxedsolutions** [comment]
Should be implemented

**Comment by andyjohansson** [comment]
Where can we test this?

**Comment by andyjohansson** [comment]
How can I test this?

**Comment by andyjohansson** [comment]
Maybe our logo should be bigger? What do you need from us?
![skarmavbild 2015-09-28 kl 13 47 48](https://cloud.githubusercontent.com/assets/4968755/10134632/8b341aa6-65e7-11e5-9dc6-e131cdbeb53c.png)

**Comment by Boxedsolutions** [comment]
Its rather complicated to have different logos for different checkouts?

**Comment by andyjohansson** [comment]
There must be a good standard?

**Comment by Boxedsolutions** [comment]
This images has a with default of 145px and about 38-45px height

**Comment by andyjohansson** [comment]
Pushing this to 2.1 release for smarter solution for cross-checkout compatibility.
