### ISSUE TITLE
Before order activation of order status change we should cross-check the invoice

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#107]
If the totals don´t mach give an error:
Swedish
1:
Order XXX kunde ej aktiveras via Billmate, belopp matchar inte: XXX1, XXX2. 
Aktivera manuellt i Billmate Online. (Öppna Billmate Online) [https://online.billmate.se/faktura/]

Multiple:
Följande ordrar kunde ej aktiveras via Billmate, beloppen matchar inte: XXX1, XXX2.
Aktivera manuellt i Billmate Online. (Öppna Billmate Online) [https://online.billmate.se/faktura/]

English
1:
Order XXX failed to activate through Billmate. The amounts don't match. Activate manually in Billmate Online. (Open Billmate Online) [https://online.billmate.se/faktura/]

Multiple:
The following orders failed to activate through Billmate: XXX1, XXX2. The amounts don't match. 
Activate manually in Billmate Online. (Open Billmate Online) [https://online.billmate.se/faktura/]

-----
Is related to #10.

**Comment by Boxedsolutions** [comment]
Implemented with a little change, when multiple invoices differs it will be complex to show all amounts due to prestashop array in cookie restriction.

**Comment by andyjohansson** [comment]
The links should be opened in a new window, e.a. target blank.

**Comment by Boxedsolutions** [comment]
Should be fixed
