### ISSUE TITLE
Add compatibility with "One page checkout for Prestashop Module"

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#108]
Also add support for get adress.

http://addons.prestashop.com/en/checkout-modules/6841-one-page-checkout-for-prestashop.html

**Comment by Boxedsolutions** [comment]
Duplicate of #105

**Comment by HansFrolich** [comment]
Which module / 3rd party product is "One Page Checkout" and Billmate compatible with? One documentation and how it works? Any recommendation? Thanks!

**Comment by Boxedsolutions** [comment]
It should be the one linked here http://addons.prestashop.com/en/checkout-modules/6841-one-page-checkout-for-prestashop.html

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by victorauren** [comment]
It doesn't appear in checkout.

**Comment by Boxedsolutions** [comment]
If it works at our Victor test it should be fixed

**Comment by victorauren** [comment]
Works fine. Tested severel times. But what about the button to click? Should we do something about it?

**Comment by Boxedsolutions** [comment]
Think we cant solve the click issue.

**Comment by victorauren** [comment]
Seems to be a OPC issue
Should we leave it for now?

**Comment by Boxedsolutions** [comment]
@victorauren Think we leave it now.

**Comment by victorauren** [comment]
Closing issue, the 2 click issue is in another ticket
