### ISSUE TITLE
Send an email with the invoice once activated

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#111]
A setting in the configuration. 
What do you think @Boxedsolutions? It hink it adds complexity to the flow.

**Comment by Boxedsolutions** [comment]
Just check a checkbox when activate Invoice. 
![invoice](https://cloud.githubusercontent.com/assets/8977650/6346297/0b7304ee-bc0f-11e4-90c8-79cdb77347e2.png)

**Comment by andyjohansson** [comment]
But is that the invoice from PS or Billmate Invoice. I want it to be the Billmate Invoice sent from the store.

**Comment by Boxedsolutions** [comment]
Ahh wget  url from link from the activate payment. It should be solvable.

**Comment by andyjohansson** [comment]
Good, we will also update so we get the link with getpaymentinfo.
