### ISSUE TITLE
If voucher is of type gift the "minus" voucher is not sent to Billmate

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#112]

**Comment by Boxedsolutions** [comment]
Should be implemented

**Comment by andyjohansson** [comment]
The name should be the name of the campaign, not the product.
![skarmavbild 2015-03-03 kl 20 02 48](https://cloud.githubusercontent.com/assets/4968755/6469882/4ec18d8e-c1e0-11e4-84fb-7fe1b766278a.png)
![skarmavbild 2015-03-03 kl 20 03 11](https://cloud.githubusercontent.com/assets/4968755/6469887/5834ea5a-c1e0-11e4-98e8-d10c3d07e168.png)

**Comment by andyjohansson** [comment]
Do we send in "rabatt" @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Yes to Billmate Online. It will be localized i think. Perhaps we should have some other "word"?

**Comment by andyjohansson** [comment]
No, it should be that, will verify the localization.

**Comment by andyjohansson** [comment]
Left is a translation issue.

**Comment by andyjohansson** [comment]
Fixed.
