### ISSUE TITLE
When you toggle the Invoice Activation on Orderstatus all is not toggled

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#115]
This one is not toggled, only the multiselect.
--> Set Order Status for Invoice Activation

**Comment by Boxedsolutions** [comment]
Could you explain this anymore?

**Comment by andyjohansson** [comment]
The span (label) is not toggled.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
When you re-toggle the status in 1.5 you get this issue --> https://v.usetapes.com/2Y9pBRg6iJ

**Comment by Boxedsolutions** [comment]
Ahh then We will need to alter the height on the boxes. When activate.

**Comment by andyjohansson** [comment]
Tell me when it´s fixed :+1:

**Comment by Boxedsolutions** [comment]
Should be fixed now
