### ISSUE TITLE
Double breadcrumbs on Billmate Bank

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#116]
Propably on Billmate Card as well.
![skarmavbild 2015-03-03 kl 10 47 44](https://cloud.githubusercontent.com/assets/4968755/6459895/431379cc-c193-11e4-9a7a-7ad472cf4dac.png)

**Comment by Boxedsolutions** [comment]
Should be fixed now.

**Comment by andyjohansson** [comment]
Fixed.
