### ISSUE TITLE
Order 153 was not activated even though the amounts match.

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#117]
![skarmavbild 2015-03-03 kl 12 46 28](https://cloud.githubusercontent.com/assets/4968755/6461758/57a44708-c1a3-11e4-9ff2-4fc2af9ef022.png)
![skarmavbild 2015-03-03 kl 12 46 43](https://cloud.githubusercontent.com/assets/4968755/6461766/6dbbafb8-c1a3-11e4-912d-33c173456e30.png)
![skarmavbild 2015-03-03 kl 12 47 04](https://cloud.githubusercontent.com/assets/4968755/6461767/7105fda4-c1a3-11e4-9bb3-dfa3073b546e.png)

**Comment by Boxedsolutions** [comment]
apiLogsid 6312. It was strange, The response said

{ "code": "5201", "message": "Billmate Error Code:5201. Invoice does not exist" }

**Comment by andyjohansson** [comment]
I understand now, test mode was enabled.

**Comment by Boxedsolutions** [comment]
I think it could be the issue.

**Comment by andyjohansson** [comment]
It was, closing, my bad.

**Comment by andyjohansson** [comment]
We will update the API with a check against the other mode and then give a better response if it exists in the other mode.
