### ISSUE TITLE
We should add another (red) error message if the invoice can't be found.

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#118]
The following error message is misleading.
![skarmavbild 2015-03-03 kl 13 16 14](https://cloud.githubusercontent.com/assets/4968755/6462225/a054930a-c1a7-11e4-905f-2a12c6a8a59e.png)

**Comment by Boxedsolutions** [comment]
Log id 6324 The first one didnt find the invoice. and log id 6325 found the invoice with status created

**Comment by andyjohansson** [comment]
Look at #120

**Comment by Boxedsolutions** [comment]
Should be implemented
