### ISSUE TITLE
Order is created before it's a order

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#12]
Se comment from client below: (In Swedish)

Bugg. När en ny order skapas så skapar inte Modulen ordern med en 
status. Då tar prestashop standard statusen "preparation in progress". 
Därefter ändrar modulen statusen. Så först blir statusen "preparation in 
progress" och ändras sen till "Billmate Faktura". Den bör skapa ordern 
direkt med statusen "Billmate Faktura".

Detta 
blir problematiskt eftersom när en vara inte finns i lager ändrar 
prestashop automatiskt statusen till "On backorder" efter att ordern 
skapats. Men Billmate modulen ändrar sedan statusen till "Billmate 
faktura" och det blir då svårt för oss att enkelt se vilka beställningar 
som finns i lager och kan skickas och vilka som inte finns då alla får 
statusen "Billmate faktura".

**Comment by Boxedsolutions** [comment]
Should be fixed with commit 2a79b84

**Comment by andyjohansson** [comment]
This one is fixed!
