### ISSUE TITLE
If error code 5220 is returned on GetPayMentInfo when trying to activate an invoice give the following error message.

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#120]
Swe;
1: Order XXX kunde ej aktiveras via Billmate, ordern finns ej i Billmate Online. Ordern finns i (test) läge däremot. Prova att ändra läge i modulens inställningar.

Multiple:
Följande ordrar kunde ej aktiveras via Billmate, ordrarna finns ej i Billmate Online: XXX1, XXX2. Ordern finns i (test) läge däremot. Prova att ändra läge i modulens inställningar. 

Eng:
1: 
Order XXX failed to activate through Billmate. The order does not exist in Billmate Online. The order exists in (test) mode however. Try changing the mode in the modules settings. 

Multiple:
The following orders failed to activate through Billmate: XXX1, XXX2. The orders does not exist in Billmate Online. The orders exists in (test) mode however. Try changing the mode in the modules settings.

Interchange the text in the brackets depending on the mode that the request is made with.

**Comment by andyjohansson** [comment]
Also in production the brackets should not be there, but I think you get that.

**Comment by Boxedsolutions** [comment]
Is it a new error code? The other one is 5201?

**Comment by Boxedsolutions** [comment]
Should be implemented
