### ISSUE TITLE
Auto height of the multiple select?

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#122]
What do you think about that function?

Either we can do it through php or through javascript.
$(function () {
   $("#multiSelect").attr("size",$("#multiSelect option").length);
});

**Comment by andyjohansson** [comment]
We maybe should have a maximum of 20 as well?

**Comment by Boxedsolutions** [comment]
Yes it would be an idea.

**Comment by andyjohansson** [comment]
Great.

**Comment by Boxedsolutions** [comment]
should be fixed now.
