### ISSUE TITLE
Don´t save multiple adresses when you checkout (logged in) if there is a exakt match

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#123]

**Comment by andyjohansson** [comment]
The name should also be
Folkbokföringsadress
Registered address

**Comment by andyjohansson** [comment]
2015-03-03

**Comment by Boxedsolutions** [comment]
As it is now. It only adds a address if the selected not matches the Registered Address.

**Comment by fermedia** [comment]
Would it work for a customer to fetch their adress to ps trough billmate? by just entering their socialnr and email in the registerform? Skipping the whole ps registerform would solve alot of issues.. in my case customers need to register in ps.. choose payment form.. enter socialnr and email etc. And after registration they hafto choose payment method and fetch their "folkbokförda adress" once again..choosing guest checkout works but still they need to enter all their info.

**Comment by Boxedsolutions** [comment]
Lets see if I understand you correct. You wonder if it is possible to fetch the address by SSN number? Which Checkout do you use? 

@andyjohansson

**Comment by fermedia** [comment]
As of what ive seen Billmate fetches the "folkbokförda adress" when the customer enters their socialnr before confirming their bought items. i would like this to happen when they choose to register as a customer in prestashop or when choosing "guest checkout" Or! Skipping the whole prestashop register process and go directly to the billmate fetch thingy when they want to check out. Sry for mumbling. Ill try to explain further tomorrow when im a bit more awake.

**Comment by fermedia** [comment]
I use the one page checkout with guest check out enabled

**Comment by andyjohansson** [comment]
There will be a setting in the guest checkout. I will add a fuature request for duture versions to implement this in the register form as well.

Is this possible @Boxedsolutions ?

**Comment by Boxedsolutions** [comment]
Yes it should be possible.

**Comment by andyjohansson** [comment]
Created a new ticket for the create account functionality, closing this one. Please look at #144 from now regarding this.
