### ISSUE TITLE
I changed store to have Euro currency instead and now I can't get any payment methods.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#125]

**Comment by Boxedsolutions** [comment]
It was just a setting in modules -> payment to allow Euro for BillmatePayment Gateway. I did see that we need to implement a better solutions for currencies in our module now. But all methods show up, which they not should

**Comment by joakim-combain** [comment]
Ok. So this is fixed then. Should we leave this open for reference or have you noted this fix on your side so we can close this issue?

**Comment by Boxedsolutions** [comment]
I guess its noted in #127
