### ISSUE TITLE
Part pay looks awful. See screenshot.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#126]
![prestashop part pay looks awful](https://cloud.githubusercontent.com/assets/10434920/6845677/527dbe14-d3b7-11e4-9228-3f19214aea41.png)

**Comment by Boxedsolutions** [comment]
Yes I guess we need to style is in someway. It also applies to Invoice i guess. 

@andyjohansson Do you have any design pictures that i can implement?

**Comment by andyjohansson** [comment]
Maybe something similar to WooCommerce?
![skarmavbild 2015-03-26 kl 13 01 49](https://cloud.githubusercontent.com/assets/4968755/6845786/560b5a90-d3b8-11e4-85e2-9e9d64b9fc0d.png)

**Comment by Boxedsolutions** [comment]
Will implement the css for this in the afternoon.

**Comment by Boxedsolutions** [comment]
Should be styled better now

**Comment by joakim-combain** [comment]
Personally I think this still looks bad. I don't like that big green button and there seems to be a lot of space between the rows. But it's better than before. So really up to @andyjohansson if it's ok.

![prestashop invoice styling](https://cloud.githubusercontent.com/assets/10434920/7112965/886cfb68-e1cf-11e4-8efd-6dea2c19a8c1.png)

**Comment by joakim-combain** [comment]
I think the text field and the checkbox should be aligned with the button. This issue is in part pay as well.

![prestashop invoice part pay not aligned](https://cloud.githubusercontent.com/assets/10434920/7251332/bdfe53e2-e82a-11e4-8745-521e7b72e7b7.png)

**Comment by andyjohansson** [comment]
Agree with @joakim-combain.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
This is fixed for 1.5. Haven't been able to test 1.6. As referenced in #140 I can't get any payment methods in 1.6.

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
