### ISSUE TITLE
If currency is not SEK, Bank and Part pay should be disabled.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#127]
Right now I get an error message from bank and part pay doesn't even show popup, seems broken almost.

If we should allow a different currency for Part pay, you need to fix the issue with part pay.

**Comment by Boxedsolutions** [comment]
Will fix a better solution for this. I think we should disable Bank and partpayment if its not SEK.
I will make a solution in the afternoon

**Comment by Boxedsolutions** [comment]
Should be implemented

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
