### ISSUE TITLE
Issues with editing products. (Prestashop issue)

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#128]
I'm trying to edit one product, but when I go to price tab on the article nothing is shown and then I can't even change back to the info tab. Could you please check if you could see if you can find the issue? I also have issues just creating a new product.

The point is to have one article with 12% vat to test discount codes.

**Comment by Boxedsolutions** [comment]
I managed to add a new product with 12 percent vat. Test 12 Procent

**Comment by Boxedsolutions** [comment]
I also changed ipod touch to 12 percent Vat

**Comment by Boxedsolutions** [comment]
Is it any more for me to do here?

**Comment by joakim-combain** [comment]
No I don't think so. Probably just some issue on my side. Closing this issue.
