### ISSUE TITLE
Can't put invoice orders. Gives Uncaught SyntaxError: Unexpected token : error in console.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#129]
It just says processing after choosing to pay with invoice.

**Comment by Boxedsolutions** [comment]
It must be some cookie issue or something. It works here :(

**Comment by joakim-combain** [comment]
But I'm running in incognito?...

I noticed that this issue will not occur if you have an address that matches the address check. If you choose a different address and get the address popup, it doesn't work. Check if you can recreate it.

**Comment by Boxedsolutions** [comment]
![skarmklipp 2015-03-26 13 36 51](https://cloud.githubusercontent.com/assets/8977650/6846297/36f254ec-d3bd-11e4-9c8a-052e1a33d560.png)
It shows here... Very strange

**Comment by Boxedsolutions** [comment]
ahh now i see the problem.

**Comment by Boxedsolutions** [comment]
It should be implemented now.

**Comment by joakim-combain** [comment]
Looks good now. Closing this issue.
