### ISSUE TITLE
I put in a random set of numbers in person number field. When I pressed proceed, nothing happend.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#131]
Should be getting an error message.

**Comment by Boxedsolutions** [comment]
In which field

**Comment by Boxedsolutions** [comment]
@andyjohansson Where do you want to show the error messages. The easiest to implement would be these nice javascript alerts ;) 

Or should we use a specific div in our payment methods? Like this
![skarmklipp 2015-04-08 10 57 24](https://cloud.githubusercontent.com/assets/8977650/7041939/1086bb60-ddde-11e4-9547-f6ef5ede8997.png)

**Comment by andyjohansson** [comment]
Specific div! :+1:

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
I can't get any error messages to show in 1.5. I'm testing in incognito so shouldn't be any issues on my side.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
I'm getting this popup when using my person number 9011203016. If I confirm it I get syntax error in console.

![prestashop popup issue](https://cloud.githubusercontent.com/assets/10434920/7610911/cb777cf8-f980-11e4-9d38-a172f179fcb5.png)

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
