### ISSUE TITLE
Problem with logos in backend.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#134]
Plugin list:

![prestashop logo missing](https://cloud.githubusercontent.com/assets/10434920/6848351/db16a2d0-d3cc-11e4-91f3-292252601926.png)

Positioning list:

![prestashop logo broken](https://cloud.githubusercontent.com/assets/10434920/6848364/eae388a4-d3cc-11e4-930a-d67a16f24fce.png)

**Comment by Boxedsolutions** [comment]
@andyjohansson Give me a General Billmate Logo.

**Comment by Boxedsolutions** [comment]
Found a logo, But I think it would be nice with a little larger

**Comment by joakim-combain** [comment]
The logos look really bad. How about we just use the cloud part of our logo? I think that's the only way this is actually going to look good, unless we can actually get the logo enlarged with the text. What do you think @andyjohansson?

![prestashop logo bad2](https://cloud.githubusercontent.com/assets/10434920/7113041/3e909a08-e1d0-11e4-9a7f-a5038dbc2a35.png)
![prestashop logo bad1](https://cloud.githubusercontent.com/assets/10434920/7113042/3e90cf32-e1d0-11e4-932e-14e3efb0ccc0.png)

**Comment by andyjohansson** [comment]
I agree, if you need any graphic work made just PM me.

**Comment by Boxedsolutions** [comment]
Changed the logo

**Comment by joakim-combain** [comment]
Looks much better :) Closing this issue.
