### ISSUE TITLE
Sort order missing.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#135]

**Comment by Boxedsolutions** [comment]
Added a way to internally sort our methods, It would not be possible to inject another payment method in between ours if we not hack the core.

**Comment by joakim-combain** [comment]
Change position on sort order in part pay.

![prestashop sort order](https://cloud.githubusercontent.com/assets/10434920/7112577/5c29c72e-e1cb-11e4-92ce-5f47ebfd25b5.png)

**Comment by joakim-combain** [comment]
Sort order doesn't work. Also seems like when I save sort order for part pay, it is saved for bank instead and when I save sort order for bank it's not saved at all. Seems really weird.

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
