### ISSUE TITLE
Min and max amount doesn't work for any payment method.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#136]

**Comment by Boxedsolutions** [comment]
Should be implemented

**Comment by joakim-combain** [comment]
I tried saving min and max with no values. It saves as 0 and 99999 for all methods but no methods are available in check out.

**Comment by Boxedsolutions** [comment]
![skarmklipp 2015-04-13 11 14 16](https://cloud.githubusercontent.com/assets/8977650/7112854/487c9f1e-e1ce-11e4-882a-a296702c97b8.png)
There was saved as min 100.

I got all payment methods with a larger amount.

**Comment by Boxedsolutions** [comment]
Ahh I see with no values its Default 0 and 99999, it was so before also.

But we might need to change that? @andyjohansson

**Comment by Boxedsolutions** [comment]
Should work

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
