### ISSUE TITLE
I tried to put an order with invoice but got Uncaught SyntaxError: Unexpected token : in console. It's just loading.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#137]
![prestashop syntax error](https://cloud.githubusercontent.com/assets/10434920/6892991/64cad844-d6c9-11e4-8208-cb89a0a5ce84.png)

**Comment by Boxedsolutions** [comment]
Should be fixed. I guess you was logged in. And had a address in your address list that matched the billmate address. We now make a check for a address that matches in the database, to prevent multiple imported addresses

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
