### ISSUE TITLE
There is an issue with two orders being created in BO when putting on order in store.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#138]
I'm assuming this is because of the order id/reference setting you implemented since the difference between the orders in BO is the order id.

Both have 7375 invoice number 
apilogsid: 15469 och 15470

**Comment by Boxedsolutions** [comment]
Did you click twice?? 

But it should not be possible that The Billmate Api send the same order number twice? @andyjohansson 
The both orders is sent exactly in the same second. 

I will check the implementation, but i think some exception needs to be thrown or error message if a store tries to send in an order twice with the same orderid
