### ISSUE TITLE
Missing logo

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#139]
![skarmavbild 2015-04-21 kl 13 57 53](https://cloud.githubusercontent.com/assets/4968755/7251751/74b7ae50-e82e-11e4-8fd5-473ead96edd8.png)

Also change text to for English to:
Accept online payments with Billmate.

**Comment by andyjohansson** [comment]
Can you also fix the translation?
![skarmavbild 2015-04-21 kl 14 05 10](https://cloud.githubusercontent.com/assets/4968755/7252370/a5a1144c-e834-11e4-8a86-d6a2ee376708.png)

**Comment by Boxedsolutions** [comment]
Should be done now

**Comment by andyjohansson** [comment]
Not translated in Swedish:
Ta betalt online med Billmate. 

"by" should also be translated to "av", if possible. Think this is a Prestashop issue.

![skarmavbild 2015-04-21 kl 15 47 57](https://cloud.githubusercontent.com/assets/4968755/7253553/e1de1ac8-e83d-11e4-982f-61e1db54f272.png)

**Comment by Boxedsolutions** [comment]
We should go through all english grammar before translate to Swedish

**Comment by andyjohansson** [comment]
Ok, let's do that the next time we get together.

**Comment by andyjohansson** [comment]
Description should have a dot after the sentence.

Ta emot betalningar med Billmate -->
Ta emot betalningar med Billmate.

**Comment by Boxedsolutions** [comment]
Should be fixed
