### ISSUE TITLE
Use the same style in front-end as in version 1.36

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#140]
2.0 (right now)
![skarmavbild 2015-04-21 kl 14 01 24](https://cloud.githubusercontent.com/assets/4968755/7251813/fdc17578-e82e-11e4-9472-0c6569539229.png)

1.36
![skarmavbild 2015-04-21 kl 14 01 20](https://cloud.githubusercontent.com/assets/4968755/7251815/009c10f0-e82f-11e4-88d8-55965ac457e0.png)

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
I can't get any payment methods in 1.6. am I doing something wrong?

**Comment by Boxedsolutions** [comment]
![skarmklipp 2015-05-12 09 43 01](https://cloud.githubusercontent.com/assets/8977650/7582169/55130758-f88b-11e4-895e-def9c4969465.png)

Try incognito. http://presta16.boxedtest.se/

**Comment by joakim-combain** [comment]
I always work in incognito when working on the web. Any idea why I can't get the payment methods?

My country says Sweden, could this be the issue that it checks for Sverige? Yours should probably say Sweden as well.

**Comment by Boxedsolutions** [comment]
Do you have selected SEK as currency? I tested with dollar and then it didnt show up

**Comment by joakim-combain** [comment]
Ah.... *face palm* Of course it is... Works now. :) Closing this issue.
