### ISSUE TITLE
Part payment with english as language are missing the value to part pay from. Also missing invoice fee ammount

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#141]
![skarmavbild 2015-04-21 kl 14 01 24](https://cloud.githubusercontent.com/assets/4968755/7251841/38d4c3b8-e82f-11e4-8bad-c07cb2da7477.png)

**Comment by Boxedsolutions** [comment]
As the invoice fee was missing was because of it was set to 0kr, But i Updated the template to not show if fee is not greater than 0

**Comment by Boxedsolutions** [comment]
If it doesnt show, it might have something with pclasses not fetched with the correct language? However I must fix this

**Comment by andyjohansson** [comment]
Great, keep me updated when you come up with a solution.

**Comment by Boxedsolutions** [comment]
Should work

**Comment by joakim-combain** [comment]
When we have english language it should say SEK not KR. for example: BILLMATE PART PAY - PAY FROM 172 KR. Here it should say SEK not KR.

Also in drop down we should change to SEK.

**Comment by Boxedsolutions** [comment]
We could leave this open a while, I saw I needed to fix the cheapest payment plan in pay from.

**Comment by Boxedsolutions** [comment]
Seems to work

**Comment by joakim-combain** [comment]
Ah, I noticed this is changed if you change currency, not language. So it's actually depending on the store settings. This issue is solved then. Closing it.
