### ISSUE TITLE
Implement the new english logos when language is english

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#142]
![skarmavbild 2015-04-21 kl 14 01 24](https://cloud.githubusercontent.com/assets/4968755/7251860/58259b3e-e82f-11e4-983f-50b5ef7b4327.png)

**Comment by Boxedsolutions** [comment]
![skarmklipp 2015-04-21 14 09 32](https://cloud.githubusercontent.com/assets/8977650/7251926/1ad67b26-e830-11e4-9a31-25c2aada40b1.png)

It should bee also. Some cache or something? As this is the new logos.

**Comment by andyjohansson** [comment]
Worked after a refresh, but the logo with "billmate" should be as big as the one before in version 1.36. DM me if you don't understand. 

Also noticed that there is missing a space between the amount and "kr". Also the value should be rounded without decimals for partpay. Invoice fee is missing in invoice as well.

**Comment by Boxedsolutions** [comment]
Its updated, i Might need to rezise the images.
