### ISSUE TITLE
Order reference

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#145]
Change this to a dropdown and the user can select which id is sent to Billmate, order id or reference id.

English: Order id used by Billmate
Swedish: Order id som används av Billmate
* Order ID (default)
* Reference ID

![skarmavbild 2015-04-21 kl 14 43 51](https://cloud.githubusercontent.com/assets/4968755/7252422/24169e46-e835-11e4-8a34-d54177d264ca.png)

**Comment by Boxedsolutions** [comment]
Should be implemented

**Comment by joakim-combain** [comment]
I have tested this and it looks good. Closing the issue.
