### ISSUE TITLE
1.5 - I get these error messages in store frontend.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#146]
Warning: include_once(): Failed opening '/var/www/presta15.boxedtest.se/public/modules/statsdata/translations/sv.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/presta15.boxedtest.se/public/classes/Translate.php on line 146

![prestashop-error-message-in-store-front](https://cloud.githubusercontent.com/assets/10434920/7581866/425ef6c4-f888-11e4-93a6-d4904d05a28e.png)

**Comment by joakim-combain** [comment]
This appeared when I changed language from English to Swedish.

**Comment by Boxedsolutions** [comment]
Should be fixed now. It was just a permission issue on the webserver

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
