### ISSUE TITLE
Style getaddress button

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/prestashop#149]

**Comment by andyjohansson** [comment]
Can the button be on the right like on other platforms we have made?

**Comment by Boxedsolutions** [comment]
like this 
<img width="1196" alt="skarmavbild 2015-09-11 kl 16 19 37" src="https://cloud.githubusercontent.com/assets/8977650/9817045/f0cbcde0-58a0-11e5-89db-30b4447658da.png">

**Comment by andyjohansson** [comment]
Can we have it on the same row as the other info?
We will cut out a bit of margin then as well (not displayed in the image below)
![fortsatt_knapp_placering](https://cloud.githubusercontent.com/assets/4968755/10131517/30ca0f28-65d1-11e5-830a-c49d0aa33822.jpg)

**Comment by Boxedsolutions** [comment]
I have now made it a little higher up.
