### ISSUE TITLE
Discounts is sent incorrectly to Billmate

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#15]
We need to update the module so that it handels all the type of discounts that Prestashop offers and make sure that they are being sent to Billmate Online correctly.

I have asked the client who reported this for examples.

Version: 1.6.9 (others might be affected as well)

**Comment by andyjohansson** [comment]
This could be related to #17

**Comment by Boxedsolutions** [comment]
Specific Prices is sent with correct amounts. 
Discount coupons seems to work also. In 1.6

**Comment by andyjohansson** [comment]
Works on card / bank - 1.6

**Comment by andyjohansson** [comment]
Works on bank - 1.6

**Comment by andyjohansson** [comment]
Works on invoice - 1.6

**Comment by andyjohansson** [comment]
Works on part payment as well, closing.
