### ISSUE TITLE
Getadress - does not output everything?

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#152]
Missing email, firstname, lastname, date of birth and phone number?
![skarmavbild 2015-07-24 kl 13 51 20](https://cloud.githubusercontent.com/assets/4968755/8873848/19d75d10-320b-11e5-8a7d-0b529082cfa6.png)

**Comment by Boxedsolutions** [comment]
Should be fixed, i dont see why we should fill in Date Of Birth

**Comment by joakim-combain** [comment]
This doesn't work with organization numbers, it seems. Is this something we bother fixing or do we mark it as a known issue?

**Comment by Boxedsolutions** [comment]
If i Test with a real organization number, I got company name, with our test companies it doesnt send data for company name.
