### ISSUE TITLE
In backend, our plugins are shown in modules and services but not in Payment

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#156]
Shouldn't our plugins be shown where the other payment options is shown?

![prestashop plugins missing](https://cloud.githubusercontent.com/assets/10434920/9514427/3fee9d20-4c9a-11e5-969c-0cdc438cf547.png)

**Comment by Boxedsolutions** [comment]
Our plugin is not verified by Prestashop, this causing this. But if you look at currencies and countries you would see our plugin.

**Comment by joakim-combain** [comment]
What do you mean if I look at currencies and countries? Do you mean in Localization - Currencies?

**Comment by Boxedsolutions** [comment]
scroll down on the page and see this. 
<img width="1060" alt="presta" src="https://cloud.githubusercontent.com/assets/8977650/9573340/9d687196-4fbb-11e5-8f54-697965c1b43a.png">

**Comment by joakim-combain** [comment]
Ahaa, now I see it. :smile:
