### ISSUE TITLE
I found some text in backend that needs to be changed.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#157]
In all plugins settings we need to change this text "Ska Billmate *payment option* vara aktiverad" to something like "Checka i för att aktivera Billmate *payment option* i checkout".

Also, in Billmate Bank it says "Aktivera Testläge" there should be a lower case t in "testläge".

**Comment by joakim-combain** [comment]
I found some more texts.

The titles need to have the same formating. "Billmate delbetalning" should be "Billmate Delbetalning" and "Billmate faktura" should be "Billmate Faktura".

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
