### ISSUE TITLE
I get a 500 server error when checking out with bank

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#158]
When I get redirected back to store I get this 500 server error.

![prestashop server error](https://cloud.githubusercontent.com/assets/10434920/9624525/126eb476-514e-11e5-8f1a-ddb3f8f80bb0.png)

**Comment by Boxedsolutions** [comment]
Should be fixed, If this occurs the solution is to uninstall our plugin and install it again

**Comment by Boxedsolutions** [comment]
But I saw I have a issue with updating status by Callback.

**Comment by Boxedsolutions** [comment]
Should bee fixed

**Comment by joakim-combain** [comment]
This issue is fixed, closing it.
