### ISSUE TITLE
We are rounding 10 SEK on shipping

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#159]
I used Test åäö as product and My carrier as shipping method and used Billmate Card.

For some reason we get double vat on the shipping. In prestashop checkout it says 40 with tax but we send 50 and then round it off.

Apilogsid: 70304
Invoice #: 834197

![prestashop shipping rounding](https://cloud.githubusercontent.com/assets/10434920/9626743/fd699f02-515f-11e5-9e78-448b6b38e2ef.png)

**Comment by Boxedsolutions** [comment]
Should fix this issue, We should se if its possible in the api side to round this -4.7999998059822e-5 which is equivalent to -0,00004.7999998059822, but I cant round it on my side as it will be a total diff on my side then,

**Comment by joakim-combain** [comment]
Ok. Should Andreas bring it here on Thursday to discuss with our developer? I feel like you are trying to do something really weird here. In your description you are having two decimals, it seems. I'm not understanding this at all, so maybe it's best if Andreas brings it when he comes here?

**Comment by Boxedsolutions** [comment]
I Will check this again, it could bee a case with rounding. Discussed this with your Developer for opencart and if i Round all values to 2 decimals it seemed that it solved it.

**Comment by joakim-combain** [comment]
Ok.

**Comment by Boxedsolutions** [comment]
It seems that it is fixed, cant reproduce

**Comment by joakim-combain** [comment]
Yep, looks like it is fixed. Closing it.
