### ISSUE TITLE
Consequent naming conventions!

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/prestashop#16]
As it is now for example Order Status Settings for Card Pay is named BCARDPAY_ORDER_STATUS_SETTINGS 

Bank pay is named 
BBANK_ORDER_STATUS_SWEDEN

There are more terrible examples, my point is that when a setting may change according to country then is it ok to append Countryname, but general settings would be better to keep consequent naming conventions

**Comment by andyjohansson** [comment]
How much work is it to fix all of these occurrences?

**Comment by Boxedsolutions** [comment]
Not much time really, but a Idea would bee to look over it for 2.0 Relase maybe.

**Comment by andyjohansson** [comment]
Ok, we do that then.

**Comment by Boxedsolutions** [comment]
Its better implemented now
