### ISSUE TITLE
Using different shipping fee depending on weight of the product is not working for invoice and part pay.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#160]
For some reason, when I use Test åäö product and use My carrier as shipping method, I always get 0 shipping in the order in backend and I get 19.90 in the invoice in billmate online.

![prestashop shipping issue invoice part pay](https://cloud.githubusercontent.com/assets/10434920/9627351/d9cfd24c-5163-11e5-8c65-f1e4fb4b6793.png)

**Comment by Boxedsolutions** [comment]
I have tested a couple of orders now with My Carrier and invoice and it seems to work

**Comment by joakim-combain** [comment]
When I test it, I'm actually not getting any shipping at all with invoice. Did you try with Invoice?

**Comment by Boxedsolutions** [comment]
Yes check invoice 8125 and 56 in Opencart

**Comment by joakim-combain** [comment]
Hmm... If you checkout as a guest, it works. But if I sign up and try to checkout, there is no shipping fee...

Login:

joakim@combain.com / Hej123

**Comment by Boxedsolutions** [comment]
Hmm... Thats strange, i Will look at it.

**Comment by Boxedsolutions** [comment]
What order is it that you did?

**Comment by joakim-combain** [comment]
I created a new account to confirm it. My orders are: 61, 62 and 63.

**Comment by joakim-combain** [comment]
Invoice # 8128, 8129 and 8130

**Comment by Boxedsolutions** [comment]
I created a account by using getAddress and it seemed to work. Check order 65, 66. 

There is something strange about if there is some delivery addresses that not having Carriers., will need to dig deep to solve it. It is prestashop that removes the shipping with setting freeshipping if there is a address with no carrier.

**Comment by joakim-combain** [comment]
Aha...

**Comment by Boxedsolutions** [comment]
Think I have solved it now,. Steps for verify, is to force display address validation popup. Use another pno than the registered address, might altering between or normal test and test with åäö.

**Comment by joakim-combain** [comment]
This issue is fixed. I haven't been able to recreate it atleast. Closing it.
