### ISSUE TITLE
Part pay is active when the total is under 100

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#162]
Partpay should be deactivated if the total amount is under 100.

Only the 3 months plan should show up if over 100 but under 200.

The 3 months and the 6 months should be active if over 200 but under 400

and all of them should be active if the total exceeds 400.

Unless we have changed our rules without me knowing it.

**Comment by Boxedsolutions** [comment]
It should work now

**Comment by joakim-combain** [comment]
I had an order with a total of 299.80 SEK, but I only got 3 months plan to choose from.

I should have gotten the 6 months too.

I used test åäö and test produkt.

**Comment by Boxedsolutions** [comment]
<img width="586" alt="skarmavbild 2015-09-07 kl 09 42 19" src="https://cloud.githubusercontent.com/assets/8977650/9711557/c5f00870-5544-11e5-9630-9718eab2fec1.png">

It should be visible according to the saved payment plans.

**Comment by joakim-combain** [comment]
No. Minamount is wrong. It should be 100 for 3 months, 200 for 6 months and 400 for 12 months.Or has billmate changed it?

**Comment by Boxedsolutions** [comment]
This is what i have got from the Api, if it not is changed since a few weeks?

**Comment by joakim-combain** [comment]
Hmm, there seems to be 6 payment plans for Billmate AB... 2 for each payment plan... @andyjohansson which ones is it that we are going with?

**Comment by andyjohansson** [comment]
Can you make a re-check with a non-test-opencart account? Think this could be due to that is a test mode? Test with a live account.

**Comment by joakim-combain** [comment]
It works now, both with test keys and live keys. Closing this issue.
