### ISSUE TITLE
We should add version number in backend to all plugins.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#163]

**Comment by Boxedsolutions** [comment]
In prestashop I dont see why really. Its visible under Modules and Services 
<img width="775" alt="skarmavbild 2015-09-03 kl 11 04 37" src="https://cloud.githubusercontent.com/assets/8977650/9654532/acb0138a-522b-11e5-9c88-e2cffa6234d7.png">

**Comment by joakim-combain** [comment]
Aha, ok. Didn't see that. Closing this issue.
