### ISSUE TITLE
Display invoice Fee correctly

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/prestashop#165]
Display invoice Fee both in Admin Order and in Order Invoice.

Steps to solve this, 
create a new table with data for order_id, invoice_fee, currency(?)

When method is invoice insert invoice_fee and order_id.

**Comment by Boxedsolutions** [comment]
How it looks in email. 

<img width="665" alt="skarmavbild 2015-09-08 kl 11 45 58" src="https://cloud.githubusercontent.com/assets/8977650/9731774/5436963c-561f-11e5-9780-e1fc75821526.png">

**Comment by Boxedsolutions** [comment]
@andyjohansson any ideas how to prettify?

**Comment by andyjohansson** [comment]
Can't we add it where in the total on the right bottom side @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Float right maybe, Pdf generation is always a bit tricky, but i will do a test.

**Comment by andyjohansson** [comment]
Super! There is no way to add it into the total sum with a function extension or something?

**Comment by Boxedsolutions** [comment]
Not without rewriting the templates, and it would not work if our clients use a custom theme :-1:

**Comment by andyjohansson** [comment]
That sucks...
Idea, could we do something like this?
https://www.prestashop.com/forums/topic/213664-guide-modifying-prestashop-15-invoice-template/

Call me, I maybe have another idea.

**Comment by Boxedsolutions** [comment]
Its a template rewrite..  And we will probably have to do this for every template that exists, or on demand for customer, We will also need to probably create a override for the controller that handles it. Its just to hope that it will come a hook for the totals to use.

**Comment by andyjohansson** [comment]
Then we should probably don´t have it on the invoice. But is it solved in the admin?

**Comment by andyjohansson** [comment]
We should try not to do special things, we can't work against the standard of the platform.

**Comment by Boxedsolutions** [comment]
Its something like this that is our possibility in Admin. 
<img width="1052" alt="skarmavbild 2015-09-08 kl 14 42 18" src="https://cloud.githubusercontent.com/assets/8977650/9735005/d93d59a2-5637-11e5-972f-dfe4845b11af.png">

**Comment by andyjohansson** [comment]
Is the total correct?

**Comment by Boxedsolutions** [comment]
The total is correct, yes.

**Comment by andyjohansson** [comment]
Ok, then the admin is OK. 
Can we develop one template for version 1.4, 1.5 & 1.6 so that we can support all the standard invoice templates? Then we make documentation on how to add it to their own templates if they have those.

**Comment by Boxedsolutions** [comment]
We have left 1.4 support with the new functionality.

**Comment by andyjohansson** [comment]
Ok, then only 1.5 & 1.6?

**Comment by Boxedsolutions** [comment]
I will create instructions on how to use them.

**Comment by andyjohansson** [comment]
Perfect, nothing fancy but like how to call them. Can we have the design something like this? But right aligned underneeth the total?

Will this work with many article rows?
![skarmavbild 2015-09-08 kl 14 49 14](https://cloud.githubusercontent.com/assets/4968755/9735136/d24e6c52-5638-11e5-8d16-3bee4bd62070.png)

**Comment by Boxedsolutions** [comment]
It adds a lot of new things that i dont like, The template is split up in different files, and my idea is to just change the totals part. Then I think most of the design the customer have will work as they want.

**Comment by andyjohansson** [comment]
In the total VAT is that including the invoice fee?

**Comment by Boxedsolutions** [comment]
yes it is. I have fixed that part before.

**Comment by andyjohansson** [comment]
In that case we don´t have to specify the invoice fee VAT. We could just then right align it underneeth the total.

**Comment by andyjohansson** [comment]
Look at this, isn´t this close enough? But will it work with many article rows to get the placement right?
![skarmavbild 2015-09-08 kl 14 57 50](ht?t.com/assets/4968755/9735298/10d95dd2-563a-11e5-8180-4a71957a267b.png)

**Comment by Boxedsolutions** [comment]
For me it sounds nice, I will then only need to css it right.

**Comment by andyjohansson** [comment]
Yes, and add the background colors and borders 😉

**Comment by Boxedsolutions** [comment]
Have added in order confirmation mail. 
<img width="610" alt="skarmavbild 2015-09-10 kl 10 28 43" src="https://cloud.githubusercontent.com/assets/8977650/9783723/d359cee2-57a6-11e5-91ea-00a698dc9060.png">

**Comment by Boxedsolutions** [comment]
If the markup in the pdf not has been the way it is it had probably been easy to do. The best i Could clearify it is like this in pdf invoice
<img width="630" alt="skarmavbild 2015-09-10 kl 10 36 50" src="https://cloud.githubusercontent.com/assets/8977650/9783886/e27fb106-57a7-11e5-8635-c0acc9c5ea2a.png">

**Comment by Boxedsolutions** [comment]
@andyjohansson Would you give any feedback

**Comment by andyjohansson** [comment]
Any possibilities to right align or anything?

**Comment by Boxedsolutions** [comment]
No its max right aligned.

**Comment by andyjohansson** [comment]
What does max right aligned mean?

**Comment by Boxedsolutions** [comment]
I cant get it more to the right. :(

Its a table structure and our hook we use is displayed in a table cell.
