### ISSUE TITLE
Prestashop birthday date is not filled when you do the get_adress

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#167]
Might as well fill it.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
Not in 1.6.1
<img width="538" alt="skarmavbild 2015-09-28 kl 10 50 21" src="https://cloud.githubusercontent.com/assets/4968755/10131194/be0debd2-65ce-11e5-8f8c-1b9545828236.png">

**Comment by Boxedsolutions** [comment]
<img width="497" alt="skarmavbild 2015-09-28 kl 10 52 24" src="https://cloud.githubusercontent.com/assets/8977650/10131237/1b329696-65cf-11e5-8d10-d450e134172d.png">

I guess its the "-" character that messes up my code

**Comment by andyjohansson** [comment]
Can you fix it?

**Comment by Boxedsolutions** [comment]
It should be fixed
