### ISSUE TITLE
Same text / info as in Magento

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#168]
<img width="1188" alt="skarmavbild 2015-09-11 kl 13 57 03" src="https://cloud.githubusercontent.com/assets/4968755/9814286/0818e9d8-588d-11e5-9b1d-ec5ea14a93a8.png">

<img width="1188" alt="skarmavbild 2015-09-11 kl 13 57 03" src="https://cloud.githubusercontent.com/assets/4968755/9814301/1dd96248-588d-11e5-8bbd-8528441d61ab.png">

The same goes for Delbetalning.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
It's not the same, see issue #180
