### ISSUE TITLE
If get adress is enabled you should NOT have to enter it in the payment window

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#169]
<img width="533" alt="skarmavbild 2015-09-11 kl 13 59 51" src="https://cloud.githubusercontent.com/assets/4968755/9814334/6405135c-588d-11e5-93e2-bb6a19ca17eb.png">
<img width="485" alt="skarmavbild 2015-09-11 kl 13 59 46" src="https://cloud.githubusercontent.com/assets/4968755/9814335/64062ce2-588d-11e5-9066-49acc5b67f94.png">

**Comment by Boxedsolutions** [comment]
Should work now.

**Comment by andyjohansson** [comment]
Could you also fix so that the pno is stored in the sessions like on other platforms?

**Comment by andyjohansson** [comment]
If I hit refresh it is gone.

**Comment by Boxedsolutions** [comment]
Will check for a cookie solution. Prestashop didnt like sessions.

**Comment by andyjohansson** [comment]
Ok, then it needs to be encrypted.

**Comment by Boxedsolutions** [comment]
Prestashop takes care of the encryption

**Comment by andyjohansson** [comment]
Good

**Comment by andyjohansson** [comment]
So it should be working now?

**Comment by Boxedsolutions** [comment]
Yes it should
