### ISSUE TITLE
When I register with a number that is connected to a private firm we should fill company field as well.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#171]
What do you think? Can we and/or should we do this?

**Comment by andyjohansson** [comment]
We can't do this just yet, we push it to 2.1.

**Comment by Boxedsolutions** [comment]
@andyjohansson I guess we should push this further.

**Comment by Boxedsolutions** [comment]
The implementation of GetAddress makes this impossible as it is today. To do this we need an extra parameter a choice if customer is a company. 

The big question is if our provider makes this possible.
