### ISSUE TITLE
Build in logoparameter

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#173]

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
Change text to the following
Logo för faktura som skickas från Billmate
Swe: Logotype som visas på fakturan
Eng: Logo to be displayed in the invoice

New text to the right: 
Swe: Ange namnet på logotypen (finns i Billmate Online). Lämna tom om ni endast har en logotype.
Eng: Enter the name of the logo (shown in Billmate Online). Leave empty if you only have one logo.

Add like 5/10 px. padding to the left of the text that is to the right (This also appends to the other input fields which has input text to the right, also the checkboxes.

![skarmavbild 2015-09-28 kl 13 43 30](https://cloud.githubusercontent.com/assets/4968755/10134545/fb0acf56-65e6-11e5-9bdd-bc0c975b8fa3.png)

**Comment by Boxedsolutions** [comment]
Should be done
