### ISSUE TITLE
Same invoice and partpayment text as in Magento

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#180]
Both title and description. Check the linebreaks and so that the text is on the same line as the text.

Invoice
![skarmavbild 2015-09-28 kl 10 45 53](https://cloud.githubusercontent.com/assets/4968755/10131109/29d11f02-65ce-11e5-9331-950b50f9d8d0.png)
![skarmavbild 2015-09-28 kl 10 45 58](https://cloud.githubusercontent.com/assets/4968755/10131113/2c15af3a-65ce-11e5-8bbb-7347e2209d73.png)

Part payment
![skarmavbild 2015-09-28 kl 10 46 55](https://cloud.githubusercontent.com/assets/4968755/10131124/48ce6b1c-65ce-11e5-8842-7c545cdaf114.png)
![skarmavbild 2015-09-28 kl 10 47 03](https://cloud.githubusercontent.com/assets/4968755/10131125/4a4ff58c-65ce-11e5-8391-b71edacd9ba1.png)

**Comment by Boxedsolutions** [comment]
Please Clarify what is the needed changes? The only thing i See is "Betalningsalternativ" that needs to be changed

**Comment by andyjohansson** [comment]
There are a lot of missmatchs, please call me when you fix it and I will clarify over the phone.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
Looks weird
![skarmavbild 2015-09-28 kl 13 28 43](https://cloud.githubusercontent.com/assets/4968755/10134289/e13d7fc6-65e4-11e5-8ac8-2eed1deb6224.png)

**Comment by Boxedsolutions** [comment]
You're welcome to see if you find some css that works better.

**Comment by andyjohansson** [comment]
Easy, just wrap it in a span with a br? Looks kinda good in responsive as well. Note the padding top: 0px on the button as well.
![skarmavbild 2015-09-28 kl 16 32 06](https://cloud.githubusercontent.com/assets/4968755/10138379/843e3c56-65fe-11e5-83dc-36964f7305da.png)

**Comment by Boxedsolutions** [comment]
Implemented this
