### ISSUE TITLE
English translation for personnummer

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#183]
Should be same as Magento.
![skarmavbild 2015-09-28 kl 11 03 22](https://cloud.githubusercontent.com/assets/4968755/10131442/8fac5df8-65d0-11e5-99e6-3e955fd7c6bf.png)
![skarmavbild 2015-09-28 kl 11 03 37](https://cloud.githubusercontent.com/assets/4968755/10131447/977fe734-65d0-11e5-925a-a5a2a6657b9b.png)

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
Fixed.
