### ISSUE TITLE
Can we have the get adress button on the same row as the input field?

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#184]
![skarmavbild 2015-09-28 kl 11 04 32](https://cloud.githubusercontent.com/assets/4968755/10131468/bd4bc5be-65d0-11e5-8398-ff3b442e89bf.png)

**Comment by andyjohansson** [comment]
Also use small "A" on Get Address so it should be
"Get address"

**Comment by Boxedsolutions** [comment]
It should be fixed

**Comment by andyjohansson** [comment]
Fix responsive part, should be on the same line in mobile view as well.
![skarmavbild 2015-09-28 kl 13 22 51](https://cloud.githubusercontent.com/assets/4968755/10134154/0bdfdd42-65e4-11e5-8bf2-8330ee8af04f.png)

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
See it's fixed.
