### ISSUE TITLE
Update currency support accordingly

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#185]
Currency code to be used for the payment according to ISO 4217. Currently supported: SEK, DKK, NOK, GBP, EUR, USD. Note: Method=16 (Bank) currently only accepts SEK and Method=4 (Part Payment) currently only accepts SEK.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
Seems to be working.
