### ISSUE TITLE
Standard sorting

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#186]
* Invoice
* Part Payment
* Card
* Bank

Can this be done?

**Comment by Boxedsolutions** [comment]
Do you want this as default?

**Comment by andyjohansson** [comment]
Yes.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
Is this only filled if we return a person and not a company?

**Comment by andyjohansson** [comment]
Otherwise, it works.

**Comment by Boxedsolutions** [comment]
The standard sorting should not depend on person or company?

But if you mean the Birthday fields I will look so we not fill it if its a company

**Comment by andyjohansson** [comment]
No, it should not. 
Good look into that.

**Comment by Boxedsolutions** [comment]
Birthday is not set for companies.

**Comment by andyjohansson** [comment]
Super, then it's done.
