### ISSUE TITLE
Fix the ugly looking save button in back-end config for Billmate

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#187]
Paypals looks quite good in their. Are there any standard?
![skarmavbild 2015-09-28 kl 13 07 15](https://cloud.githubusercontent.com/assets/4968755/10133917/e4f493a0-65e1-11e5-9d90-f92d3b49fbf3.png)

**Comment by Boxedsolutions** [comment]
Better looking button

**Comment by andyjohansson** [comment]
Skip the border color as well.
![skarmavbild 2015-09-28 kl 16 57 18](https://cloud.githubusercontent.com/assets/4968755/10139174/03cc2160-6602-11e5-8a08-7f647dd5ef94.png)
![skarmavbild 2015-09-28 kl 16 57 36](https://cloud.githubusercontent.com/assets/4968755/10139185/096a8396-6602-11e5-854d-f7f8f05b5d43.png)

**Comment by Boxedsolutions** [comment]
Its done
