### ISSUE TITLE
Look over the responsiveness

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#189]
![skarmavbild 2015-09-28 kl 13 20 47](https://cloud.githubusercontent.com/assets/4968755/10134115/c4582cc2-65e3-11e5-8a2f-6b3c7ab28c89.png)

**Comment by Boxedsolutions** [comment]
Should be done

**Comment by andyjohansson** [comment]
Verified on iPhone 5 and it looks good.
