### ISSUE TITLE
Seems to be missing some padding / margin on row for social security number

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#190]
Tighter to the one below than all the others.

![skarmavbild 2015-09-28 kl 13 23 54](https://cloud.githubusercontent.com/assets/4968755/10134189/427cbd52-65e4-11e5-9f50-48e6d429f49c.png)

**Comment by Boxedsolutions** [comment]
Should be done

**Comment by andyjohansson** [comment]
Fixed.
