### ISSUE TITLE
Do we need option "välj" for order id? Just set one as default if not set?

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#191]
The one which is standard should be the one that is standard for other payment methods such as paypal and so on.

![skarmavbild 2015-09-28 kl 13 25 30](https://cloud.githubusercontent.com/assets/4968755/10134217/7bfbb0ce-65e4-11e5-9137-323f65da775b.png)

**Comment by Boxedsolutions** [comment]
This is in our common settings template, either Remove all Choose labels or not.

**Comment by andyjohansson** [comment]
Remove the "choose".

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
Seems fixed.

**Comment by andyjohansson** [comment]
Which one is the default?

**Comment by Boxedsolutions** [comment]
To Send Order Id

**Comment by andyjohansson** [comment]
Great, closing.
