### ISSUE TITLE
Change text activate invoice Billmate Onlone

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#193]
Aktivera fakturor med inställd status på Billmate Online
-->
 Aktivera fakturor med inställd status i Billmate Online automatiskt
![skarmavbild 2015-09-28 kl 16 02 24](https://cloud.githubusercontent.com/assets/4968755/10137544/577dc118-65fa-11e5-95fa-31aa6094b992.png)

**Comment by Boxedsolutions** [comment]
Should be fixed
