### ISSUE TITLE
Clarify invoice fee setting

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#195]
Swe: Fakturaavgift ex. moms (SEK)
Eng: Invoice fee ex. VAT (SEK)
![skarmavbild 2015-09-28 kl 16 59 20](https://cloud.githubusercontent.com/assets/4968755/10139256/4ecbd598-6602-11e5-981e-298c270c8b06.png)

**Comment by andyjohansson** [comment]
Can we have (kr) after the input field? And then only as SEK without the ()?

**Comment by Boxedsolutions** [comment]
Hmm. If its $ it would bee the correct position in front of the field, its a lot of logic only to display currency. But it should be possible to add the currency sign to the right.

**Comment by Boxedsolutions** [comment]
<img width="346" alt="skarmavbild 2015-09-28 kl 17 13 55" src="https://cloud.githubusercontent.com/assets/8977650/10139692/6670cc6a-6604-11e5-942e-586b6b6221ae.png">

**Comment by Boxedsolutions** [comment]
Fixed as above

**Comment by andyjohansson** [comment]
Remove SEK from left.
Replace kr on right with SEK.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
SUPER!
