### ISSUE TITLE
Do we need to display the error_billmateinvoice?

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#196]
Just toggle the display parameter of the css?
![skarmavbild 2015-09-28 kl 17 04 55](https://cloud.githubusercontent.com/assets/4968755/10139428/172e160e-6603-11e5-8194-55f94982adb0.png)

Also padding bottom of 10px of the billmateinvoice class? Looks a lot better when it's not that big.
This also applies to the part payment option.
![skarmavbild 2015-09-28 kl 17 05 53](https://cloud.githubusercontent.com/assets/4968755/10139464/3fce4a20-6603-11e5-87ec-7db16f27623a.png)

**Comment by andyjohansson** [comment]
Only padding 10 px bottom when it's open.

**Comment by Boxedsolutions** [comment]
Fixed this logic

**Comment by andyjohansson** [comment]
Not the padding-bottom?

**Comment by Boxedsolutions** [comment]
I removed padding and replaced with padding bottom 10px when its visible.

**Comment by andyjohansson** [comment]
Can't see it?
![skarmavbild 2015-09-28 kl 17 36 22](https://cloud.githubusercontent.com/assets/4968755/10140366/77b0c57c-6607-11e5-91e0-2d2d040b5588.png)

**Comment by Boxedsolutions** [comment]
Det ligger i payment-form 
<img width="1262" alt="skarmavbild 2015-09-28 kl 17 37 50" src="https://cloud.githubusercontent.com/assets/8977650/10140494/145f6220-6608-11e5-9ca7-f56545a7c338.png">
<img width="1256" alt="skarmavbild 2015-09-28 kl 17 38 06" src="https://cloud.githubusercontent.com/assets/8977650/10140497/16fd9baa-6608-11e5-9526-764128cd5bbe.png">

**Comment by andyjohansson** [comment]
I'm talking about this one, https://v.usetapes.com/0aKsoiGv1P

Too much padding bottom on that element.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
Fixed, release!
