### ISSUE TITLE
Activate Get address is wrongly translated.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#202]
It says "Aktivera Hämta address" but it should say "Aktivera Get address" alternatively "Aktivera Hämta adress".

**Comment by andyjohansson** [comment]
Remove the dubbel d in "adress".

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by victorauren** [comment]
Looks right in both Swedish and English
Closing issue

**Comment by victorauren** [comment]
Address is spelled wrong when have english as an active language. Se attached image
![address](https://cloud.githubusercontent.com/assets/14887835/12610257/f6c435c2-c4e6-11e5-9c57-a1be59efcdd8.png)

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by victorauren** [comment]
Looks great
closing issue
