### ISSUE TITLE
Returns and Credit from prestashop Admin

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/prestashop#208]

**Comment by Boxedsolutions** [comment]
To be checked when we got answer regarding api and updatepayment.

**Comment by victorauren** [comment]
When credit parts of the order in the backend I get the message "Du m�ste ge heltalsv�rden i f�ljande f�lt: total med moms, total utan moms och total moms.
"

Roundingissue in updatePayment, se attached image (API 234700)
![update](https://cloud.githubusercontent.com/assets/14887835/12610033/ca4c4620-c4e5-11e5-9a79-399b38887811.PNG)

**Comment by Boxedsolutions** [comment]
Try this again. Have changed a little logics

**Comment by victorauren** [comment]
Works ok, but in the activatePayment you get this error: 
"code": "5208",
	"message": "Det g\u00e5r inte att aktivera en icke skapad faktura.",
	"logid": "310143"

Same in OPC as original checkout

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by victorauren** [comment]
Yes it works fine. Test some more

**Comment by victorauren** [comment]
Been tested several times and different scenarios. Works good
Closing issue
