### ISSUE TITLE
Check design 1.6.1 payment options.

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/prestashop#210]

**Comment by Boxedsolutions** [comment]
Seems that the only change there is is that it uses a img tag again. Only ps16 will then use image in css. 

Then it seems like i have to use legacy display for newer than 1.6.1

**Comment by Boxedsolutions** [comment]
Just check to see if payment options is displayed correctly

**Comment by victorauren** [comment]
It looks good in checkout and also in backend.
Is this what you mean?

**Comment by Boxedsolutions** [comment]
Yes.

**Comment by victorauren** [comment]
ok then i close the issue
