### ISSUE TITLE
Remove personalnumber in Invoice when using getAdress-function

### ISSUE THREAD

**Issue by victorauren** [Billmate/prestashop#213]
[SWE] När man matar in personnumret i "Hämta adress" så finns personnumret redan och det ska därför plockas bort när man väljer faktura eller delbetalning som betalningsmedel. Liknande som körs i Magento. 

[ENG] When enter your personal number when using "Get Address"-function the personalnumber is already entered once and when chosing Invoice or partpayment, there is no need to enter it again. So we can remove that information. It is similar like it is in Magento.

**Comment by Boxedsolutions** [comment]
Should be implemented

**Comment by victorauren** [comment]
If I leave Get Adress Empty a popup-window appear and says that personalnumber is missing. I have to get to the top and add a personalnumber and click save. 
Is that correct? @Boxedsolutions

**Comment by Boxedsolutions** [comment]
We might need to see if we could do the error in better way. But not so easy in Prestashop :)

**Comment by Boxedsolutions** [comment]
I think we have to rethink this as some shops still use multistep checkout, which may make some trouble

**Comment by victorauren** [comment]
It seems that getAdress dosn't work in multistep checkout or in one step checkout (original Prestashop)
Works in OPC

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by victorauren** [comment]
Can be a OPC issue that is not possible to fix?
Works fine in prestashop original checkout

**Comment by Boxedsolutions** [comment]
Seems to work

**Comment by victorauren** [comment]
Yes it does work now
