### ISSUE TITLE
Taxrate on shipping fee is placed under roundings

### ISSUE THREAD

**Issue by victorauren** [Billmate/prestashop#214]
When order is made with taxrate on the shipping fee, the sum is placed under Roundings. The sum on the shipping without tax is right, but just the sum of the taxrat on the shipping fee is placed under roindings on the invoice. And also the taxrate is set to 0, but that is wrong.
![fraktmoms](https://cloud.githubusercontent.com/assets/14887835/12318799/65b9be7e-ba9d-11e5-9dc7-d2764afa473f.png)

Se attached picture

**Comment by Boxedsolutions** [comment]
@victorauren Can we reproduce on presta16.boxedtest.se ?

**Comment by Boxedsolutions** [comment]
Is it possible to make this on presta16.boxedtest.se?

**Comment by victorauren** [comment]
I will try @Boxedsolutions

**Comment by victorauren** [comment]
I have reproduced this on teststore( ljus)

**Comment by Boxedsolutions** [comment]
Might be solved with infinite Address check

**Comment by victorauren** [comment]
Tested severel times and it works 
closing issue
