### ISSUE TITLE
Partpayment plans is showed in both swedish and english

### ISSUE THREAD

**Issue by victorauren** [Billmate/prestashop#217]
When English is the chosen language, it gets paymentplans in both swedish and english in the configurationarea. If swedish is the selected language it show only the information in swedish.

**Comment by Boxedsolutions** [comment]
@victorauren How is it in frontend, It searches for active languages and fetches english and swedish if both is active.

**Comment by victorauren** [comment]
It shows only the chosen language. So it works as it should

Closing issue
