### ISSUE TITLE
Roundings VAT

### ISSUE THREAD

**Issue by victorauren** [Billmate/prestashop#219]
The error with VAT is presented. Se attached image

Checkout:
![moms](https://cloud.githubusercontent.com/assets/14887835/12614558/f86062ce-c500-11e5-85de-0911f8ce0170.png)

APi
![log](https://cloud.githubusercontent.com/assets/14887835/12614604/46b5cf0e-c501-11e5-8a4d-2006237d2f7c.PNG)

**Comment by Boxedsolutions** [comment]
applied the rounding fix for totals. Please check again.

**Comment by victorauren** [comment]
works fine now
