### ISSUE TITLE
New Feature? - Animation on process

### ISSUE THREAD

**Issue by victorauren** [Billmate/prestashop#221]
[Eng]Got a suggestion from a customer that we should put an animation on the text "Processing" when order is placed in the checkout. Some customers can think that the page has stopped working.  

[Swe]Fick ett förslag från en kund att vi skulle animera testen "Bearbetar..." när man lägger en order. Kan vara bra för att kunden inte ska uppfatta att sidan hängt sig om det skulle ta lång tid för ordern att gå igenom.

**Comment by Boxedsolutions** [comment]
Should be visible now

**Comment by victorauren** [comment]
This feature is working perfect. Clossing issue
