### ISSUE TITLE
Billmate Cardpay - Support Plugin - No install needed! on Deliveryslips and Invoices

### ISSUE THREAD

**Issue by fermedia** [Billmate/prestashop#222]
The text "Billmate Cardpay -
Support Plugin - No install
needed!" ends up on payment-metodhs in Deliverslips and Invoices.

![image](https://cloud.githubusercontent.com/assets/11261123/12786499/b216afbc-ca91-11e5-884b-19238e913425.png)

![image](https://cloud.githubusercontent.com/assets/11261123/12786512/bddf367a-ca91-11e5-9ed4-551bba1de137.png)

**Comment by Boxedsolutions** [comment]
Can we reproduce this?

**Comment by victorauren** [comment]
Yes it is reproduced in severel orders on testsite (ljus)

**Comment by Boxedsolutions** [comment]
Will you take a second look :P

**Comment by victorauren** [comment]
Work better, but it shows twice on invoice now. Se attached image
![paymethod](https://cloud.githubusercontent.com/assets/14887835/14204331/e61f1db8-f803-11e5-9788-4504f18c57c2.png)

**Comment by victorauren** [comment]
But only one one invoice, not both.

**Comment by Boxedsolutions** [comment]
Think we cant do anything for this

**Comment by victorauren** [comment]
We discussed this and we leave this as it is. As we agreed, it works fine. And also, as Presta should work, it creates just one order in backend when out of stock. 
Closing issue
