### ISSUE TITLE
If shipping is free/zero, skip sending shipping info

### ISSUE THREAD

**Issue by victorauren** [Billmate/prestashop#224]
If an order is made and the shipping is zero/free, then don't send the shipping with the order. If an order with amount 0 is processed it will have tax 0, and it can't be changed later. 
You can change shipping, but the tax rate will remain zero. So if the shipping is zero, don't send it with the order.

**Comment by Boxedsolutions** [comment]
Free shipping isnt sent to Billmate.

**Comment by victorauren** [comment]
When shipping is free or 0 it doesn't send in shipping to API. That should delete this issue. 
Clossing the issue
