### ISSUE TITLE
Normalize currency code with strtoupper

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/prestashop#228]

**Comment by Boxedsolutions** [comment]
Should be implemented. Works if payment methods is visible

**Comment by victorauren** [comment]
It sends in SEK even if the code is sek. So i guess this is right?

**Comment by Boxedsolutions** [comment]
It was not the issue. The issue was that payment method was not visible if currency codes was in lowercase letters.

**Comment by victorauren** [comment]
Then I will check that again

**Comment by victorauren** [comment]
All paymentmethods are visible even if the ISO code is sek or SEK. This works as it should
Closing issue
