### ISSUE TITLE
Remake the adresscheck popup

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#229]
Check for error code 2403 on addPayment instead of making a getAdress call

**Comment by Boxedsolutions** [comment]
Check if address is verified correctly

**Comment by victorauren** [comment]
When put an order, it makes an addPayment with the addresses i entered (different billing and shipping) then the pop-up appears and after that it change addresses as before. 
Is this correct?

**Comment by Boxedsolutions** [comment]
Yes it looks correct.

**Comment by victorauren** [comment]
In the teststore with OPC it makes 2 addpayment and two getadress before the final addPayment. 
Find these different in logs:

![invoice_check_diff](https://cloud.githubusercontent.com/assets/14887835/14136160/ae83df4a-f661-11e5-8a81-2cade0d3ee25.png)

**Comment by victorauren** [comment]
Same different in the getAdress log

**Comment by Boxedsolutions** [comment]
Retry

**Comment by victorauren** [comment]
It has just 2 addPayments now, as it should be. These looks good. But it still has 2 getAdress. The flow:
addPayment 1 - getAdress - getAdress- addPayment 1-updatePayment

**Comment by Boxedsolutions** [comment]
Yes it needs to be that way. 
First if customer checkout and has wrong address, it makes an getAddress shows the popup, when click yes, the url get a variable geturl=yes and getaddress is run before addPayment to update customer address.

**Comment by victorauren** [comment]
I see, I will test invoicepayment and this feature more to verify that it works.

**Comment by victorauren** [comment]
Can we save the first getAdress and skip the second getAdress?
So the flow will be addPayment-getAdress-addPayemnt-updatepayment.

**Comment by Boxedsolutions** [comment]
What if customer changes Social Security number after first check?

**Comment by victorauren** [comment]
Yeah, true, But if I press "Pay" addPayement is made, and then getAdress. If I then return and change, doesn't it do the procedure from beginning again? So If I make a change it do addP - getA- addP- UpdateP?

**Comment by Boxedsolutions** [comment]
What if customer doesnt accept cookies? As Prestashop store in client cookies.

**Comment by victorauren** [comment]
All set
closing issue
