### ISSUE TITLE
Cardpay and bankpay with OPC

### ISSUE THREAD

**Issue by victorauren** [Billmate/prestashop#233]
When clicking on cardpay or bankpay and then pay, nothing is happend. It has something to do with removing one of the addPayment in a previous issue.

**Comment by Boxedsolutions** [comment]
Should be solved with commit 7ea5442

**Comment by victorauren** [comment]
Works with both bank and card now. 
Still problem with return to store with bankpayment

**Comment by Boxedsolutions** [comment]
How is it with callbacks and accept now

**Comment by victorauren** [comment]
I returns to the store but not to the "Order completed" page, it the returns to order history-page. This only happens whit bankpayment

**Comment by Boxedsolutions** [comment]
It should now return correkt

**Comment by victorauren** [comment]
Yes it does,

closing issue
