### ISSUE TITLE
Make clearer checkout 

### ISSUE THREAD

**Issue by victorauren** [Billmate/prestashop#234]
I was thinking about if we should make checkout clerarer. If you see attached image, it list the different paymentoptions. If i press card I go directly to paymentwindow for card. If I press invoice, it says continue. Perhaps on invoice it should say "Pay" or similiar?

**Comment by Boxedsolutions** [comment]
Why? There is no need to add a extra click for customer to checkout? And what image? :)

**Comment by victorauren** [comment]
But the text on Invoice is "Fortsätt" and perhaps if we change to "Slutför". "Fortsätt" tells thi customer to continue the order, in the next step, "Slutför" is saying it is the last step??
Card and bank is fine.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by victorauren** [comment]
Looks good, Should it be changed i english? I think that in english it works with proced.

**Comment by Boxedsolutions** [comment]
Think it work with english to :)

**Comment by victorauren** [comment]
Ok closing issue
