### ISSUE TITLE
Payment Invoice - Infinite loop

### ISSUE THREAD

**Issue by victorauren** [Billmate/prestashop#235]
When using Invoice as a pay method, and I use different shipping-adress it creates an infinite loop. We hade the same issue before we changed the flow, that it should do a addPaymnet first. And now it creates ALOT in API-logs. (42 pages)

What happens is that i make a addPayment followed by two getAdress, and then it do it all over again, and again. 

See no. 306831 - 307247 ( closed the browser here)

This is exactly what I did, 
1. Entered a adress for billing
2. Entered a different adress for shipping
3. Choosed pay with invoice
4. Infinite Loop started

This is recreated at our teststore

**Comment by Boxedsolutions** [comment]
Is it only for OPC? I couldnt reproduce on presta16 store @victorauren

**Comment by victorauren** [comment]
Yes, in this case. Another customer use the standard checkout and has the same issue @Boxedsolutions

**Comment by Boxedsolutions** [comment]
Testagain

**Comment by victorauren** [comment]
Tested several times adn now it is working
Closing issue
