### ISSUE TITLE
Doubleclick pay-button creates 2 orders

### ISSUE THREAD

**Issue by victorauren** [Billmate/prestashop#236]
When clicking multiple times on pay-button in checkout it creates two orders in Billmate Online. Using this on OPC. 

This can't happen i PS original checkout because Prestashop lock the pay-button after first click

See invoice 265111 and 276508
and also  100501 and 498863

**Comment by Boxedsolutions** [comment]
Check again

**Comment by victorauren** [comment]
Still adds two orders
Using partpayment in this test

**Comment by Boxedsolutions** [comment]
Seems to be a OPC issue

**Comment by victorauren** [comment]
Perhaps we should move this to another release, or at least leave it out of this release to have more time to investigate?

**Comment by Boxedsolutions** [comment]
Sounds good

**Comment by Boxedsolutions** [comment]
Pushing to future
