### ISSUE TITLE
Title InvoiceService

### ISSUE THREAD

**Issue by victorauren** [Billmate/prestashop#238]
I should be presented something like "Faktura vid extern fakturaadress" or "Fakturaservice vid extern fakturaadress"

Any other suggestions?

**Comment by Boxedsolutions** [comment]
Its client specific as its not is for All clients, My bet is that customer needs to edit translations their self.
@victorauren

**Comment by victorauren** [comment]
But Fakturaservice is better then Invociceservice.

**Comment by Boxedsolutions** [comment]
Should be translated

**Comment by victorauren** [comment]
Still says invoiceservice

**Comment by victorauren** [comment]
FIxed
closing issue
