### ISSUE TITLE
Use standard formating for the payment methods

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#24]
See the following:
http://cl.ly/image/1r1V412v3d1I/Ska%CC%88rmavbild%202015-01-21%20kl.%2015.20.43.png

**Comment by Boxedsolutions** [comment]
Applies to 1.6 which use Bootstrap theming.

**Comment by andyjohansson** [comment]
Can we test this @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Should work

**Comment by andyjohansson** [comment]
Looks great on 1.6

**Comment by andyjohansson** [comment]
On 1.4 we should make it look like the other payment options.
![skarmavbild 2015-01-26 kl 10 44 54](https://cloud.githubusercontent.com/assets/4968755/5897787/63e56960-a548-11e4-965f-c1c4af73fe9b.png)

**Comment by andyjohansson** [comment]
And on 1.5 it looks like the other ones. So we need to update for 1.4 (see above).

**Comment by andyjohansson** [comment]
Is now related to #11

**Comment by andyjohansson** [comment]
Just fix the centering of the text.

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
