### ISSUE TITLE
Choose more than one orderstatus to credit or activate an order i BO

### ISSUE THREAD

**Issue by victorauren** [Billmate/prestashop#244]
Can we add multichoice of orderstatus when activate and credit payment in backend. Example Activeta an order if it has both send and Deliviered?

@Boxedsolutions

**Comment by Boxedsolutions** [comment]
Yes, Control click

**Comment by victorauren** [comment]
Out client needed that the. It only save one options now

**Comment by Boxedsolutions** [comment]
Should work now,

**Comment by victorauren** [comment]
Can't save several orderstatus. I just has one marked.

**Comment by Boxedsolutions** [comment]
Should be in hotfix-2.1.2

**Comment by victorauren** [comment]
Works fine
closing issue
