### ISSUE TITLE
Choose companyfield in checkout

### ISSUE THREAD

**Issue by victorauren** [Billmate/prestashop#246]
Can we add feature to choose companyfield to be visible only if there is a company that is doing the order (in the adresscheck)

If there is a company registered on the number in getAdress then show companyfield?

**Comment by Boxedsolutions** [comment]
It could break the checkout functionality

**Comment by victorauren** [comment]
Ok perhaps this is up for discussion then

**Comment by Boxedsolutions** [comment]
Solved with external module
