### ISSUE TITLE
Invoice payment stops working

### ISSUE THREAD

**Issue by victorauren** [Billmate/prestashop#247]
When I enter pno, use getAdress and then change firstname by adding another name it stops working when pressing pay. No popup is present. 
It just says "processing"

In the logs it makes a addPayment 1 and then a getaddress. No more. (318057 - addPayment, 318058 - getAdress) The addpayement has the error "Angivet förnamn matchar inte våra register. Förväntat förnamn xxxxx. Tillhandahållet förnamn: xxx zzz"

In the console of the browser I get this error: 
![ljustema](https://cloud.githubusercontent.com/assets/14887835/14418569/dec74324-ffbf-11e5-8a25-a4270db41cc8.png)

Recreated in test-site.

@Boxedsolutions

**Comment by Boxedsolutions** [comment]
Ahh I see, Should be an easy fix.

**Comment by Boxedsolutions** [comment]
Should be fixed. The name is now compared better.

**Comment by victorauren** [comment]
Works fine
Closing issue
