### ISSUE TITLE
No popup just error

### ISSUE THREAD

**Issue by ghost** [Billmate/prestashop#248]
When creating new account and add another zip-code then the one registered it gets following error: "Angivet postnummer matchar ej våra register. Förväntad zip: 12345. Tillhandahållet: 54321". No pop-up apperas. Just error-message

LogID:319546

**Comment by Boxedsolutions** [comment]
See if this relates to #247

**Comment by victorauren** [comment]
Perhaps, but the different is that it doesn't stops when logo processing appears. I jsut do an addPayment but not getAdress

**Comment by victorauren** [comment]
The other issue #247 works

**Comment by Boxedsolutions** [comment]
Are You signed in or guest?

**Comment by victorauren** [comment]
signed in now. And it is only zip-code that behaves like this

**Comment by victorauren** [comment]
Tested without an account and it is still the same
Will try in a new Prestashop aswell

**Comment by victorauren** [comment]
Same in new Presta with original checkout

**Comment by kalorifri** [comment]
Cant reproduce, seems to be fixed and released.
