### ISSUE TITLE
Creating double invoices backend test-site

### ISSUE THREAD

**Issue by victorauren** [Billmate/prestashop#249]
The only different evry time it creates double invoices in backend is the Query_string and request_URI

It has $get_url=yes in both lines

Se loggs when 2 invoices is created: 
319585
319481
When only on is created:
319551
319546

**Comment by victorauren** [comment]
It has the same issue in regular Prestashop and only invoice payment

**Comment by Boxedsolutions** [comment]
Hmm get_url=yes means clicked yes on address popup

**Comment by Boxedsolutions** [comment]
Ahh it could be the issue..

**Comment by victorauren** [comment]
Now I know how to trigger this
When you create a order with the new flow (addPayment-getAdress-getAdress-addPayment-updatePayment) it creates the double invoices

**Comment by victorauren** [comment]
I have tested and tested and it seems to work now. Tested i 4 different stores (and different versions of Prestashop) with the same result. 
Will do a overall test again to verify that everything works before we can release the hotfix
