### ISSUE TITLE
Add the name of the variable product title to the name that is being sent to Billmate Online

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#25]

**Comment by andyjohansson** [comment]
![skarmavbild 2015-01-21 kl 15 48 09](https://cloud.githubusercontent.com/assets/4968755/5838093/f944a1dc-a184-11e4-8236-2d3539708ea8.png)

**Comment by Boxedsolutions** [comment]
Should work

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
