### ISSUE TITLE
Display invoice or invoiceservice in backend

### ISSUE THREAD

**Issue by victorauren** [Billmate/prestashop#254]
When using the function that switch between invoice or invoiceservice when using other billing adress in checkout it has to have correct method sent to backend. Now it show Billmate Invoice even if it send it as a Invoice service.

**Comment by Boxedsolutions** [comment]
Did my solution work?

**Comment by victorauren** [comment]
Yes, but we need to discuss where on the invoice it should be visible. And if it works with Project-field we have to consider to rename it. Also the issue with how many characters we should use before it cuts/make new row. It works with 48 charactaters, but it make new row in invoice. And if you delete 4-5 characters then it shows in one row. And if you add more, then it is cut on presented in one row. 
(se attached image) 
![meddelande](https://cloud.githubusercontent.com/assets/14887835/15419033/a348641e-1e63-11e6-9c53-c87afddb55a5.png)

@Boxedsolutions @andyjohansson

**Comment by victorauren** [comment]
This works fine and is approved by customer
Closing issue
