### ISSUE TITLE
Check if order is pending when activating

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#265]
If order is pending, throw exception.
If order is created, activate.

**Comment by Boxedsolutions** [comment]
It should be this logic already. If the order is pending the client would se a error message.

**Comment by kalorifri** [comment]
I have tested.
We need to fix so Billmate payment module for Prestashop use Billmate API version 2.1.8 for support for the status Pending when using addPayment.

**Comment by MattiasNilsson** [comment]
Old issue closing.
