### ISSUE TITLE
Only able to activate order if payment status is "Betalning godkänd"

### ISSUE THREAD

**Issue by kalorifri** [Billmate/prestashop#267]
The only way to order to be activated on set orderstauts is if order first have orderstaus "betalning godkänd". If payment method is set to have an other orders status on payment, activation wont work.

Must have set this value to "Betalning godkänd" 
![image](https://cloud.githubusercontent.com/assets/11087406/18437326/b8f5d32a-78fc-11e6-81a5-15c85f5ef310.png)

Or else order wont be activated when order status later is set to example: 
![image](https://cloud.githubusercontent.com/assets/11087406/18437364/dfe6e492-78fc-11e6-9e7a-8d34201b42fb.png)

Should be able to set another value for "Sätt orderstatus" and the order still should be activated on order status "Skickad"

**Comment by Boxedsolutions** [comment]
What is the benefits of this? I have seen a lot of stores that have own statuses. To make it easier for store owners to list orders per payment method and payment status.

**Comment by kalorifri** [comment]
The issue is that you can not set an other status than "Betalning godkänd" if you want the order to be activated in billmate online.
For example, if "Sätt orderstatus" is set to "Betalning godkänd" and the order get that status in Prestashop, the order is activated.
But if "sätt orderstatus" instead is set to "Skickad" and order get that status in Prestashop, order is not activated.

"Sätt orderstatus" only work when "Betalning godkänd" is set.
If it cant be fixed so you can select other status för "sätt orderstus" then you should not be able to select other option.

**Comment by Boxedsolutions** [comment]
You should not set Betalning Godkänd, more correct approach should be to set Skickad. Because its more convenient as the invoice should be sent when order is shipped?

**Comment by kalorifri** [comment]
The problem is that you cant to that you described is the best practice, it does not work.
Thats the issue.

**Comment by kalorifri** [comment]
My bad.
It seems to work just fine.
