### ISSUE TITLE
Method 2 is sent 

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#268]
Method 2 is called even though the file to enable this does not exist. @Boxedsolutions knows how to fix this now.

Push hotfix as soon as it is tested by @kalorifri.

**Comment by Boxedsolutions** [comment]
Should be fixed in 195501d

**Comment by kalorifri** [comment]
Tested and confirmed the issue is fixed.

**Comment by kalorifri** [comment]
Fixed in release 2.1.7
