### ISSUE TITLE
Set default value for Billmate cardpayment Betalningsåtgärd

### ISSUE THREAD

**Issue by kalorifri** [Billmate/prestashop#277]
Make sure that if you in Billmate settings have not selected any "Betalningsåtgärd" set "Reservera belopp"  as default.
As it is now, you can save without have set Betalningsåtgärd.

![image](https://cloud.githubusercontent.com/assets/11087406/19858607/61fcf7ae-9f82-11e6-8a97-e28178b9f643.png)

**Comment by andyjohansson** [comment]
Good catch @kalorifri
