### ISSUE TITLE
Sometimes the checkmark for "my email is correct" get displayed wrong

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#28]
See the thing in action:
https://v.usetapes.com/4JGtx7Ndj7

**Comment by andyjohansson** [comment]
No reload or anything in progress when it occurs...

**Comment by andyjohansson** [comment]
This is for both invoice and part payment.

**Comment by andyjohansson** [comment]
What´s the status on this @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Should be fixed, only appears in 1.6. Checkboxes for email correct was moving before.

**Comment by joakim-combain** [comment]
This issue is fixed. I couldn't recreate it atleast. Closing it.

**Comment by andyjohansson** [comment]
I also took a look at it and it seems to bo OK.
