### ISSUE TITLE
Auto activate in AddPayment when Betalningsåtgärd is set to Debitera belopp

### ISSUE THREAD

**Issue by kalorifri** [Billmate/prestashop#280]
If Betalningsåtgärd is set to Debitera belopp then order should be autoactivated on addPayment.

![image](https://cloud.githubusercontent.com/assets/11087406/19967715/d8529bba-a1d1-11e6-8492-4e43819e4a64.png)

**Comment by Boxedsolutions** [comment]
No it should be activated in callback/accept due to otherwise the shops order number will not be correct. 

So it should be a activatePayment call after the order

**Comment by kalorifri** [comment]
It works, it where never an issue.
