### ISSUE TITLE
Speed improvements for freight handling on Billmate Checkout page

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#289]

**Comment by andyjohansson** [comment]
@Boxedsolutions will handle this after handoff from @kalorifri

**Comment by andyjohansson** [comment]
Överlämning ej genomförd ännu.

**Comment by andyjohansson** [comment]
What is the status on this issue @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Work in Progress, Have to investigate how to solve it.

**Comment by kalorifri** [comment]
Released in 3.1.0
