### ISSUE TITLE
On the checkout page for partpayment the design is a bit dense, make it more like the invoice

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#29]
![skarmavbild 2015-01-21 kl 15 51 09](https://cloud.githubusercontent.com/assets/4968755/5838140/69fef59e-a185-11e4-8bd1-b3795afd10dd.png)

**Comment by Boxedsolutions** [comment]
![screenshot from 2015-01-24 00 52 30](https://cloud.githubusercontent.com/assets/8977650/5884835/53342a84-a363-11e4-9100-364146f66bb7.png)

Something like that? 
@andyjohansson

**Comment by andyjohansson** [comment]
Looks better, but it should say "Personnummer / organisationsnummer:"
There should also be some padding between "Personnummer:" and the textfield.

There also seems to be some translation stuff that needs some work.
And the text "Choose I confirm my order to Order Köpvillkor delbetalnig" should be:
"I confirm my order and accept the terms and conditions for part payment" There should also be a checkbox for that one and have the same styling as "Min e-postadress."...

**Comment by andyjohansson** [comment]
What´s the status on this one @Boxedsolutions?

**Comment by joakim-combain** [comment]
This issue is fixed, there are some issues left but those are noted in a different issue. Closing.
