### ISSUE TITLE
Module doesn't work with Knowband - SuperCheckout

### ISSUE THREAD

**Issue by HansFrolich** [Billmate/prestashop#299]
Hi,
When I use Billmate in standard Prestashop 1.7 check out then it works. But the layout etc doesn't look good so we upgraded to SuperCheckout, which is a very nice module. However then Billmate stops working, with the message "PAYMENT METHOD: TECHNICAL ERROR- Request Failed".
I downloaded Klarna and that module worked...
Our site is: vonbonliving.com
SuperCheckout: https://addons.prestashop.com/en/express-checkout-process/18016-knowband-one-page-checkout-social-login-mailchimp.html
What could be the error?
MVH, Hans Frölich, hansfrolichgbg@gmail.com
![billmate error](https://user-images.githubusercontent.com/17982954/45405181-1fb7f580-b662-11e8-9d98-61c5a467a18b.png)

**Comment by fjcastilloc** [comment]
HELLO! Did you resolve this issue?
Regards

**Comment by MattiasNilsson** [comment]
Old issue closing.
