### ISSUE TITLE
On the checkout page for partpayment - "Villkor för faktura" should be "Villkor för delbetalning"

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#30]
![skarmavbild 2015-01-21 kl 15 51 09](https://cloud.githubusercontent.com/assets/4968755/5838155/8f5c9134-a185-11e4-83fe-02fd4ceb5f43.png)

**Comment by joakim-combain** [comment]
I've checked this and it looks good. Closing this issue.
