### ISSUE TITLE
Change formating of text on part payment options

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#31]
The text should be "3 månaders delbetalning - 188,18 SEK / månad"
![skarmavbild 2015-01-21 kl 15 51 09](https://cloud.githubusercontent.com/assets/4968755/5838175/b24258d2-a185-11e4-8678-194963bbdf02.png)

**Comment by Boxedsolutions** [comment]
Should be fixed in english. But should work in swedish also

**Comment by andyjohansson** [comment]
Closing, not relevant anymore since it´s not on a separate page anymore.
