### ISSUE TITLE
Layout the error messages according to coding standard with margin and padding

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#32]
This is true for both part payment and invoice.
![skarmavbild 2015-01-21 kl 15 57 35](https://cloud.githubusercontent.com/assets/4968755/5838246/4f99ea32-a186-11e4-94b3-57a6e1e15e77.png)

**Comment by Boxedsolutions** [comment]
Should be fixed in commit a725de3

**Comment by andyjohansson** [comment]
Verified on Invoice.

**Comment by andyjohansson** [comment]
Not working currently on part payment.
![skarmavbild 2015-01-21 kl 21 31 53](https://cloud.githubusercontent.com/assets/4968755/5844546/f44234a8-a1b4-11e4-9e45-5f6d332c6036.png)

**Comment by Boxedsolutions** [comment]
![partpayerror](https://cloud.githubusercontent.com/assets/8977650/5857010/7f2a11ec-a248-11e4-882c-c92ad10fb0c6.png)

Working on partpayment

**Comment by andyjohansson** [comment]
Tested on both 1.5 and 1.6?

**Comment by andyjohansson** [comment]
Can you verify @joakim-combain ?

**Comment by joakim-combain** [comment]
this is fixed. However, there is an issue in 1.5 where I put the store to english and the error message is in swedish. But I think we already have an issue on that. What's status of fixing this?

**Comment by Boxedsolutions** [comment]
It will be a translation i will do later on. Its necessary to create translation for everthing in all available lagnuages. 

Its not as easy as it is in the other e-commerce platforms.

**Comment by andyjohansson** [comment]
Can you define "later on" Is it for 1.35 or should we postpone it?

**Comment by Boxedsolutions** [comment]
It will be the last thing I do in 1.35. Because its possible that we find more to translate.

**Comment by andyjohansson** [comment]
Ok, good to know.

**Comment by joakim-combain** [comment]
Should we close this or keep it open?

**Comment by andyjohansson** [comment]
We keep it open.

**Comment by andyjohansson** [comment]
This translation we will leave also to the new API, do you think so as well @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Sound like a plan

**Comment by andyjohansson** [comment]
Ok, will close this one.
