### ISSUE TITLE
The close text in the lightbox for partpayment and invoice should be localized

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#34]
Should be "close" or "stäng" depending on language.
![skarmavbild 2015-01-21 kl 16 09 57](https://cloud.githubusercontent.com/assets/4968755/5838482/13bfb12a-a188-11e4-83ea-873ddc7c5afa.png)

**Comment by Boxedsolutions** [comment]
Could you check this

**Comment by joakim-combain** [comment]
The link to get the terms doesn't work.

**Comment by Boxedsolutions** [comment]
![skarmklipp 2015-04-08 10 44 17](https://cloud.githubusercontent.com/assets/8977650/7041782/a4facbf8-dddc-11e4-9f56-1b53ed3ac738.png)
![skarmklipp 2015-04-08 10 47 04](https://cloud.githubusercontent.com/assets/8977650/7041783/a4fe2ff0-dddc-11e4-8ec8-6ea8e827f3ba.png)
Seems to work here.

**Comment by joakim-combain** [comment]
I know I'm picky, but the link stretches out over the space. This issue is for both Invoice and Part pay.

![prestashop picky issue](https://cloud.githubusercontent.com/assets/10434920/7113401/99a002fa-e1d3-11e4-9014-037926c75467.png)

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
