### ISSUE TITLE
Find a way that keeps invoice product out of Discount.

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/prestashop#36]
As the billmate fee is a product. Therefore its possible that discounts ar applied to the fee also. 

Look up

**Comment by andyjohansson** [comment]
We shouldn't have the discount fee as a product there should be a better way to do this, I think we talked about this function before.

**Comment by Boxedsolutions** [comment]
Its implemented

**Comment by Boxedsolutions** [comment]
We dont use product for the invoice fee any more
