### ISSUE TITLE
The module is not registred as a payment gateway

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#37]
![skarmavbild 2015-01-21 kl 21 53 01](https://cloud.githubusercontent.com/assets/4968755/5844899/f43f4416-a1b7-11e4-984e-81c218a0d8a2.png)

**Comment by Boxedsolutions** [comment]
Info about this The BO > Modules > Payment page has 4 sections to

1) The very top module list will only display 'approved' payment modules.  Those are generally only modules developed by Prestashop.  Your module will not appear here

**Comment by andyjohansson** [comment]
Ok, closing.
