### ISSUE TITLE
Validate that login credentials work

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#38]

**Comment by Boxedsolutions** [comment]
Could you verify. Its validated on save.

**Comment by joakim-combain** [comment]
I got this error when I put in 7271 606250886062:

Notice: Undefined index: billmateError in /var/www/presta15.boxedtest.se/public/cache/smarty/compile/b8/24/c8/b824c8d5c9a4e47c5455aaab8927e75a3b790074.file.error.tpl.php on line 30 Notice: Trying to get property of non-object in /var/www/presta15.boxedtest.se/public/cache/smarty/compile/b8/24/c8/b824c8d5c9a4e47c5455aaab8927e75a3b790074.file.error.tpl.php on line 30

**Comment by Boxedsolutions** [comment]
Great with real error information. Should be fixed now

**Comment by joakim-combain** [comment]
That's strange... I put in 7271 and it gives me no error message. If I leave ID empty it returns an error, if I put 7270 606250886061 I get a billmate error. Only ID seems to have issue of having no error message if Billmate ID is wrong.

**Comment by Boxedsolutions** [comment]
I use the errors provided by Billmate but have no added a check so a error message is shown when ID is empty.

**Comment by joakim-combain** [comment]
Seems to be a lot of issues with these error messages.

If you leave Secret empty, no error message is shown.
If you put 7271, no error message is shown.
If you put 606250886060, no error message is shown.

How come the billmate error codes are not shown?

**Comment by Boxedsolutions** [comment]
![Uploading Skärmklipp 2015-04-21 10.08.48.png . . .]()
Tried with 7271 

It should be fixed now

**Comment by joakim-combain** [comment]
Commented on this issue in #83.

**Comment by Boxedsolutions** [comment]
Fixed so that it work to change credentials

**Comment by joakim-combain** [comment]
I'm able to change to 727 as Billmate ID. This should generate an error message I think. It does for Billmate Key if I try to save 60625088606.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
this issue is fixed. Closing it.
