### ISSUE TITLE
PHP notice in BillmateGateway

### ISSUE THREAD

**Issue by MattiasNilsson** [Billmate/prestashop#389]
`[Wed Jan 20 08:40:40.734123 2021] [php7:notice] [pid 68296:tid 1948] [client ::1:49367] PHP Notice:  Undefined variable: e in C:\\xampp\\htdocs\\Prestashop\\modules\\billmategateway\\library\\clients\\Client.php on line 28
`

**Comment by KFoobar** [comment]
Fixed
