### ISSUE TITLE
Possible to create an order multiple times in BO. 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/prestashop#392]
Would you make an order in the session open up the checkout in prestashop and then open up a second order in a second tab is it possible to finish both orders in quick succession, this will result in two seperate success URL pages, only one of them will create an order in the Prestashop store, however both will create orders in BO. One that has a correct order ID and one that has a very odd looking one. 

How to reproduce:
1: Create an order and go to the last page of the checkout.
2: Create a new tab and go to the last page of the checkout again.
3: Finish the first checkout.
4: Before the first checkout has successfully loaded the thank you page finish the second checkout.

**Comment by andyjohansson** [comment]
But, isn't this a Billmate Checkout issue instead of a PrestaShop issue? The Billmate Checkout should block this behaviour?

**Comment by OskarOstlund** [comment]
That is a fair point actually, I will close down the issue and create a ticket for our checkout instead.

**Comment by andyjohansson** [comment]
Reopen since there are a minor improvment to be included.

**Comment by andyjohansson** [comment]
What pull request are linked to this issue @KFoobar?

**Comment by OskarOstlund** [comment]
What exactly is this minor improvement included in PS 101? I saw no difference when I tested at the very least but it did not break anything compared to before.

**Comment by KFoobar** [comment]
@OskarOstlund The change that has been made regarding this issue is that the extension now cancels the second payment if an order has already been created by the first payment.

**Comment by OskarOstlund** [comment]
Tested and approved. 
This works in when one has access to callbacks.

**Comment by andyjohansson** [comment]
Great, closing issue.
