### ISSUE TITLE
Adding more items before finishing checkout causes issues due to the finish page. 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/prestashop#393]
It is possible to actually add items to your cart after you have started the checkout. Would you then finish the checkout you already opened will we get the original order saved in BO but the completed order gets sent into the prestashop store. An error message appears for the merchant looking at the order in the admin but this still causes some confusion for the user as no error message appears on the thank you site and in Bo does the order not look particularly odd despite the differences in it and the old order. 

How to reproduce: 
1: Start a purchase and go to the last step in the checkout.
2: Open up a new tab.
3: In the new tab add a new item to your order.
4: Finish the order in the first tab.

**Comment by andyjohansson** [comment]
@OskarOstlund if you try to reproduce this error with a built in payment method, how does PrestaShop handle this? Just curios if this is a PrestaShop or a Billmate issue...

**Comment by OskarOstlund** [comment]
This seems to be a billmate issue in my tests. Every time I made an order in the native payment module do you get the correct number of items in the successURL and in the store.
