### ISSUE TITLE
Billmate Checkout without https problems

### ISSUE THREAD

**Issue by MattiasNilsson** [Billmate/prestashop#396]
If I do not have https active in the store, I can not proceed when I click on the pay button in PS 1.7.X. When I do the same thing in PS 1.6, I come to a "guest checkout page" where it says go on to the payment. When I click there I will come to Billmate Checkout again and if I make the purchase I will go to the page again to go to payment (infinity loop)

The problem that is created when this happens is that the orders are still created in Online Billmate, but for the customer and the store, it has no idea that a payment has been created.

The best thing would have been if you could still get to the thank you page and that the order is tried to be created even though the callback is not sent.

If this cannot be resolved, we may display an error message on the Billmate Checkout page stating that https is required to run Billmate Checkout. 

1.7x looks like this when i click pay without https

![image-2021-01-28-10-29-03-495](https://user-images.githubusercontent.com/1718315/106150323-84187880-617b-11eb-92d3-1b3a83d837b8.png)

**Comment by andyjohansson** [comment]
Please involve me in this process since I think I can bring value to the discussion.

**Comment by KFoobar** [comment]
The SSL setting is hard coded to true in the extension. 

Do the web service accepts non-SSL requests or is SSL mandatory?

**Comment by andyjohansson** [comment]
I will get back to you with correct answer ASAP.
