### ISSUE TITLE
Orders are not created in PrestaShop even though transaction is complete in Checkout

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#399]
### Brief explanation
We have customers who do not receive a confirmation from the store when they have placed an order and that the order is never created in PrestaShop back office.

### Expected behaviour
When an order is placed, the store will create the order in the back office and that the customers will receive a thank you email and come to the thank you page.

### Billmate comments
Paul has researched a bit and come to these conclusions
1: The difference between when it did not work and when it worked is that when it did not work, it was possibly the customer's first purchase and not remembered.Customer.Billing.company and Customer.Billing.street2 are included and are empty.It may be possible for the store to make a mistake when updating the address in Billmate Checkout. Either by going to step 2 or changing the address manually, or maybe clicking "not you" and then going to step 2 again.Examples if applicable

### Troubleshooting Results
Api log id: 39902504 - Did not work
Api log id: 41754607 - Did not work
Api log id: 40202467 - Did not work

Migrated from JIRA as PS-100.

**Comment by OskarOstlund** [comment]
I found an issue that might be related to this but the outcome is identical at the very least. When I deleted my customerlist and then tried to create an order were no order created in Prestashop even if it shows up in BO.

**Comment by OskarOstlund** [comment]
Tested and approved. 
---
Both alternatives suggested by paul seems to work and all orders I tested seems to work at the very least.
