### ISSUE TITLE
Verify against Prestashop Automatic Module Validator

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#4]

**Comment by Boxedsolutions** [comment]
![validation](https://cloud.githubusercontent.com/assets/8977650/5859994/bb15e30a-a25e-11e4-9b12-07efa3848be8.png)
Validation right now :+1:

**Comment by andyjohansson** [comment]
Ok, we need to through this one for 2.0 instead. Will move this until that one. We want 0 errors on 2.1 release.

**Comment by Boxedsolutions** [comment]
![prestaprogress2015-01-24](https://cloud.githubusercontent.com/assets/8977650/5887452/cb61d70e-a3d1-11e4-9366-912e9fec4725.png)
Lite framsteg

**Comment by Boxedsolutions** [comment]
![skarmklipp 2015-04-21 11 56 09](https://cloud.githubusercontent.com/assets/8977650/7249815/795970e4-e81d-11e4-81d1-9954b2dedf83.png)
Progress pic, most of the reported stuff is on Billmate.php and such files.

**Comment by Boxedsolutions** [comment]
@andyjohansson Your decision on how we should proceed

**Comment by andyjohansson** [comment]
Could you download a full report of it so that I can go through it?

**Comment by andyjohansson** [comment]
?

**Comment by andyjohansson** [comment]
What is the status on this one now before the release?

**Comment by Boxedsolutions** [comment]
<img width="309" alt="skarmavbild 2015-09-28 kl 12 29 01" src="https://cloud.githubusercontent.com/assets/8977650/10133309/94e78ade-65dc-11e5-9982-4c9d5d22c26e.png">

**Comment by andyjohansson** [comment]
We will have to fix all of these for the 2.1 release since we are going to get PrestaShop certified.

**Comment by MattiasNilsson** [comment]
Closed due to almost 5 year old issue.
