### ISSUE TITLE
Remove in the install script the order status that is created for Billmate

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#40]
Billmate : Payment accepted
Billmate : Payment in pending verification

**Comment by andyjohansson** [comment]
@Boxedsolutions will research.

**Comment by andyjohansson** [comment]
What the status on this one @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
I see more pros and cons to keep them. 
With a order state a order can be marked as Paid and more. Its a loot easier to hook the right order when we later on Activates Invoices, and Credit invoices in Webshop Administration. 

Nearly every module add own order states for the different payment states.And a person with read and write trouble, has easier to see which payment method that was used for the order. For example if a customer want to track how many sales they have with different payments.

**Comment by andyjohansson** [comment]
Ok, we keep it then, closing.
