### ISSUE TITLE
PrestaShop order are created incorrectly v 3.8.0 with PrestaShop 1.6.X

### ISSUE THREAD

**Issue by stefanliden** [Billmate/prestashop#401]
**Brief explanation**
PrestaShop v1.6.1.13 Billmate gateway version v1.8.0 customer has received invoice orders where the order status has  payment error. This then creates a problem since Customers receive an email that the payment failed and the merchant sees that the payment is invalid even though it has been created correctly in PrestaShop.

**Expected behaviour**
If an order has been received correctly by Billmate and can be activated, it should not have status payment error as status in the Prestashop store.

**Video and / or images**

 ![image](https://user-images.githubusercontent.com/13320183/107378615-6f79a000-6aec-11eb-93e4-2bd8525c8765.png)
 ![image](https://user-images.githubusercontent.com/13320183/107474661-0721d180-6b73-11eb-9077-4149e34fd717.png)

///
 ![image](https://user-images.githubusercontent.com/13320183/107474344-7a771380-6b72-11eb-9581-8aafb79c9a3a.png)
 ![image](https://user-images.githubusercontent.com/13320183/107475050-cc6c6900-6b73-11eb-8d6c-8749bc7cace3.png)

![image](https://user-images.githubusercontent.com/13320183/107474482-b5794700-6b72-11eb-9aca-b6251f8b7386.png)
![image](https://user-images.githubusercontent.com/13320183/107475380-50265580-6b74-11eb-9bd6-1ee614895b3b.png)

**Examples if applicable**
Below you see the update Payment and error message on the order and in the store's logs
![image](https://user-images.githubusercontent.com/13320183/107378541-5b35a300-6aec-11eb-9d45-29fc1658ec85.png)

**Comment by andyjohansson** [comment]
Seems like we are sending number 1455 when it should be 2340? But I don't understand why this order havent been created in PrestaShop? The updatePayment call should be made AFTER the order is created in PrestaShop?

**Comment by andyjohansson** [comment]
But are we sure that is the correct failed log id? Since the timestamp does not match?

**Comment by andyjohansson** [comment]
@stefanliden

**Comment by stefanliden** [comment]
I have updated the information regarding the problem my theory that it was updatePayment was not the cause as this was related to another order that has been created correctly in PS.

**Comment by andyjohansson** [comment]
Awaiting customer error logs.
