### ISSUE TITLE
PHP compatibility  <= 5.5 incorrectly v3.8.0 

### ISSUE THREAD

**Issue by stefanliden** [Billmate/prestashop#402]

**Comment by andyjohansson** [comment]
User acceptance testing on latest 1.6 and 1.7.

**Comment by stefanliden** [comment]
This branch gives me error code 500 in the callback and no order is creating in the PrestShops BO. I have tested master version after and there it the callbacks is working fine.

![image](https://user-images.githubusercontent.com/13320183/108369762-37fda880-71fc-11eb-8bd4-35f85469aede.png)


My test store is using:  PHP 7.4 PrestaShop 1.6.4

**Comment by KFoobar** [comment]
@stefanliden Do you have any error logs from either Prestashop or your web server that could provide a clue where the error occurs?

**Comment by KFoobar** [comment]
@stefanliden Can you change PHP version? Try 7.2 or 7.1.

**Comment by stefanliden** [comment]
@KFoobar lowest php i have is 7.3 its turn on now 👍

**Comment by KFoobar** [comment]
@stefanliden I have successfully placed a few orders in your store with commit 5a9bd46 from 2021-02-18. Please verify if the issue is fixed.
