### ISSUE TITLE
When I try to check out with invoice and click to confirm my order, nothing happens. There should be an address popup here.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#41]
When I try to check out, it's just loading.

I get an error message in console, see screenshot.

https://drive.google.com/file/d/0B8nZhLflMVxNOGFHMU1CRkM2b3M/view?usp=sharing

**Comment by andyjohansson** [comment]
1.6 i believe?

**Comment by joakim-combain** [comment]
This is for the 1.6, yes.

**Comment by joakim-combain** [comment]
This issue is actually in 1.5 also.

**Comment by joakim-combain** [comment]
This is only for invoice, works in part pay.

**Comment by Boxedsolutions** [comment]
Should work now.

**Comment by joakim-combain** [comment]
It works now. Closing this issue.
