### ISSUE TITLE
1.5 - Card is not working for me, it's not showing up in checkout.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#42]
Settings looks good, so there shouldn't be any problems.

**Comment by joakim-combain** [comment]
![modules prestashop](https://cloud.githubusercontent.com/assets/10434920/5852784/6f0cffe4-a21c-11e4-9021-5239ed1cac33.png)
![order teststore](https://cloud.githubusercontent.com/assets/10434920/5852783/6f0cea68-a21c-11e4-8a58-f6f73c06ba82.png)

**Comment by Boxedsolutions** [comment]
Its a rather stupid condition check if Cardpay should show up or not. 

Its check for store country if its set.

Added Store country now.

**Comment by joakim-combain** [comment]
Ah, it's fixed now. Great! Closing the issue.
