### ISSUE TITLE
1.5 - Bank is messing shipping and invoice address in BO.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#43]
Seems like you are not sending shipping and invoice address.

Invoice number: 6545

This is what the api logs look like:

09:18:07 769655: Array
(
    [0] => 0.5.9
    [1] => PHP:Prestashop:1.35
    [2] => 
    [3] => 1
    [4] => 
    [5] => 
    [6] => 5-14219182
    [7] => 
    [8] => Array
        (
            [email] => Joakim@efinance.se
            [telno] => 0730000000
            [cellno] => 0730000000
            [fname] => Joakimåäö
            [lname] => Teståäö
            [company] => 
            [careof] => 
            [street] => Testgatanåäö
            [zip] => 12345
            [city] => Testortåäö
            [country] => SWEDEN
        )

    [9] => Array
        (
            [email] => Joakim@efinance.se
            [telno] => 0730000000
            [cellno] => 0730000000
            [fname] => Joakimåäö
            [lname] => Teståäö
            [company] => 
            [careof] => 
            [street] => Testgatanåäö
            [house_number] => 
            [house_extension] => 
            [zip] => 12345
            [city] => Testortåäö
            [country] => SWEDEN
        )

    [10] => 2.69.146.244
    [11] => 0
    [12] => SEK
    [13] => 209
    [14] => en
    [15] => 7270
    [16] => sjEgJ3OQD+Lah/4SEEN5AdxJXC+umymzoWDGiEH/sEcAkpK4m97x4ozGQrp01YJq11KmH6HdScK0I75kTpDYPw==
    [17] => 2
    [18] => -1
    [19] => Array
        (
            [0] => Array
                (
                    [qty] => 1
                    [goods] => Array
                        (
                            [artno] => demo_4
                            [title] => MacBook
                            [price] => 117057
                            [vat] => 25
                            [discount] => 0
                            [flags] => 0
                        )

                )

            [1] => Array
                (
                    [qty] => 1
                    [goods] => Array
                        (
                            [artno] => demo_5
                            [title] => iPod touch
                            [price] => 31689
                            [vat] => 25
                            [discount] => 0
                            [flags] => 0
                        )

                )

            [2] => Array
                (
                    [qty] => 1
                    [goods] => Array
                        (
                            [artno] => 
                            [title] => Rabatt
                            [price] => -15172
                            [vat] => 25
                            [discount] => 0
                            [flags] => 0
                        )

                )

            [3] => Array
                (
                    [qty] => 1
                    [goods] => Array
                        (
                            [artno] => 
                            [title] => Shipping
                            [price] => 875
                            [vat] => 25
                            [discount] => 0
                            [flags] => 40
                        )

                )

        )

    [20] => 
    [21] => Array
        (
            [delay_adjust] => 1
        )

    [22] => Array
        (
        )

    [23] => Array
        (
        )

    [24] => Array
        (
        )

    [25] => Array
        (
            [time] => 1421918286.6467
        )

    [26] => Array
        (
            [0] => Array
                (
                    [cust_no] => 0
                    [creditcard_data] => Array
                        (
                            [fc] => module
                            [module] => billmatebank
                            [controller] => validation
                            [id_lang] => 1
                            [order_id] => 5-14219182
                        )

                )

        )

)

09:18:07 769655: Order will be created
09:18:07 769655: TEXT TO HASH: MacBook:iPod touch:Rabatt:Shipping:
09:18:07 769655: SECRET GET: sjEgJ3OQD+Lah/4SEEN5AdxJXC+umymzoWDGiEH/sEcAkpK4m97x4ozGQrp01YJq11KmH6HdScK0I75kTpDYPw== Diggest: sjEgJ3OQD+Lah/4SEEN5AdxJXC+umymzoWDGiEH/sEcAkpK4m97x4ozGQrp01YJq11KmH6HdScK0I75kTpDYPw== TEXT: MacBook:iPod touch:Rabatt:Shipping:606250886062
09:18:07 769655: Paid or credit. Module: Transaction id: Query is: SELECT orderid_real number FROM mexcCustomerorders WHERE mm3servicesid='6062' and date>='2015-01-22 09:15:07' and json_data like '%%'
09:18:07 769655: To pay is checked
09:18:07 769655: Values are prepared
09:18:07 769655: Logo is checked
09:18:07 769655: Customer values are fixed
09:18:07 769655: order is inserted: 54351 Micro time is:1421918287.9475
09:18:08 769655: Invoice ids are updated
09:18:08 769655: Notifystoreowner is done
09:18:08 769655: Response: Array
(
    [0] => 3253
    [1] => 3253
    [2] => 1
    [3] => 6545
)

09:18:30 941383: Array
(
    [0] => 0.5.9
    [1] => PHP:Prestashop:1.35
    [2] => 
    [3] => 0
    [4] => 
    [5] => 
    [6] => 5-14219182
    [7] => 
    [8] => Array
        (
            [email] => 
            [telno] => 
            [cellno] => 
            [fname] => 
            [lname] => 
            [company] => 
            [careof] => 
            [street] => 
            [zip] => 
            [city] => 
            [country] => 
        )

    [9] => Array
        (
            [email] => 
            [telno] => 
            [cellno] => 
            [fname] => 
            [lname] => 
            [company] => 
            [careof] => 
            [street] => 
            [house_number] => 
            [house_extension] => 
            [zip] => 
            [city] => 
            [country] => 
        )

    [10] => 94.126.216.80
    [11] => 0
    [12] => 0
    [13] => 209
    [14] => 138
    [15] => 7270
    [16] => sjEgJ3OQD+Lah/4SEEN5AdxJXC+umymzoWDGiEH/sEcAkpK4m97x4ozGQrp01YJq11KmH6HdScK0I75kTpDYPw==
    [17] => 2
    [18] => -1
    [19] => Array
        (
            [0] => Array
                (
                    [qty] => 1
                    [goods] => Array
                        (
                            [artno] => demo_4
                            [title] => MacBook
                            [price] => 117057
                            [vat] => 25
                            [discount] => 0
                            [flags] => 0
                        )

                )

            [1] => Array
                (
                    [qty] => 1
                    [goods] => Array
                        (
                            [artno] => demo_5
                            [title] => iPod touch
                            [price] => 31689
                            [vat] => 25
                            [discount] => 0
                            [flags] => 0
                        )

                )

            [2] => Array
                (
                    [qty] => 1
                    [goods] => Array
                        (
                            [artno] => 
                            [title] => Rabatt
                            [price] => -15172
                            [vat] => 25
                            [discount] => 0
                            [flags] => 0
                        )

                )

            [3] => Array
                (
                    [qty] => 1
                    [goods] => Array
                        (
                            [artno] => 
                            [title] => Shipping
                            [price] => 875
                            [vat] => 0
                            [discount] => 0
                            [flags] => 40
                        )

                )

        )

    [20] => 
    [21] => Array
        (
            [delay_adjust] => 1
        )

    [22] => Array
        (
        )

    [23] => Array
        (
        )

    [24] => Array
        (
        )

    [25] => Array
        (
            [time] => 1421918309.0649
        )

    [26] => Array
        (
            [0] => Array
                (
                    [cust_no] => 0
                    [creditcard_data] => Array
                        (
                            [status] => 0
                            [order_id] => 5-14219182
                            [error_message] => Approved
                            [amount] => 167842
                            [currency] => SEK
                            [mac] => a631c5b9fa788635654f880593d942e808e6193c47f67650215a4b811270d28e
                            [time] => 2015-01-22 10:18:29.446452
                            [test] => YES
                            [merchant_id] => 7270
                            [pay_method] => handelsbanken
                            [trans_id] => 800823210
                        )

                    [status] => Paid
                )

        )

)

09:18:30 941383: TEXT TO HASH: MacBook:iPod touch:Rabatt:Shipping:
09:18:30 941383: SECRET GET: sjEgJ3OQD+Lah/4SEEN5AdxJXC+umymzoWDGiEH/sEcAkpK4m97x4ozGQrp01YJq11KmH6HdScK0I75kTpDYPw== Diggest: sjEgJ3OQD+Lah/4SEEN5AdxJXC+umymzoWDGiEH/sEcAkpK4m97x4ozGQrp01YJq11KmH6HdScK0I75kTpDYPw== TEXT: MacBook:iPod touch:Rabatt:Shipping:606250886062
09:18:30 941383: Paid or credit. Module:handelsbanken Transaction id:800823210 Query is: SELECT invoiceid_real number FROM mexcCustomerinvoices WHERE mm3servicesid='6062' and date>='2015-01-22 09:15:30' and json_data like '%800823210%'
09:18:30 941383: To pay is checked
09:18:30 941383: Values are prepared
09:18:30 941383: Logo is checked
09:18:30 941383: Customer values are fixed
09:18:30 941383: Will make second check for double transaction: SELECT invoiceid_real number FROM mexcCustomerinvoices WHERE mm3servicesid='6062' and date>='2015-01-22 09:15:30' and json_data like '%800823210%'
09:18:30 941383: invoice is inserted: 1337974 Micro time is:1421918310.4282
09:18:31 830492: Array
(
    [0] => 0.5.9
    [1] => PHP:Prestashop:1.35
    [2] => 
    [3] => 
    [4] => 
    [5] => 
    [6] => 5-14219182
    [7] => 
    [8] => Array
        (
            [email] => Joakim@efinance.se
            [telno] => 0730000000
            [cellno] => 0730000000
            [fname] => Joakimåäö
            [lname] => Teståäö
            [company] => 
            [careof] => 
            [street] => Testgatanåäö
            [zip] => 12345
            [city] => Testortåäö
            [country] => SWEDEN
        )

    [9] => Array
        (
            [email] => Joakim@efinance.se
            [telno] => 0730000000
            [cellno] => 0730000000
            [fname] => Joakimåäö
            [lname] => Teståäö
            [company] => 
            [careof] => 
            [street] => Testgatanåäö
            [house_number] => 
            [house_extension] => 
            [zip] => 12345
            [city] => Testortåäö
            [country] => SWEDEN
        )

    [10] => 2.69.146.244
    [11] => 0
    [12] => 0
    [13] => 209
    [14] => 138
    [15] => 7270
    [16] => sjEgJ3OQD+Lah/4SEEN5AdxJXC+umymzoWDGiEH/sEcAkpK4m97x4ozGQrp01YJq11KmH6HdScK0I75kTpDYPw==
    [17] => 2
    [18] => -1
    [19] => Array
        (
            [0] => Array
                (
                    [qty] => 1
                    [goods] => Array
                        (
                            [artno] => demo_4
                            [title] => MacBook
                            [price] => 117057
                            [vat] => 25
                            [discount] => 0
                            [flags] => 0
                        )

                )

            [1] => Array
                (
                    [qty] => 1
                    [goods] => Array
                        (
                            [artno] => demo_5
                            [title] => iPod touch
                            [price] => 31689
                            [vat] => 25
                            [discount] => 0
                            [flags] => 0
                        )

                )

            [2] => Array
                (
                    [qty] => 1
                    [goods] => Array
                        (
                            [artno] => 
                            [title] => Rabatt
                            [price] => -15172
                            [vat] => 25
                            [discount] => 0
                            [flags] => 0
                        )

                )

            [3] => Array
                (
                    [qty] => 1
                    [goods] => Array
                        (
                            [artno] => 
                            [title] => Shipping
                            [price] => 875
                            [vat] => 25
                            [discount] => 0
                            [flags] => 40
                        )

                )

        )

    [20] => 
    [21] => Array
        (
            [delay_adjust] => 1
        )

    [22] => Array
        (
        )

    [23] => Array
        (
        )

    [24] => Array
        (
        )

    [25] => Array
        (
            [time] => 1421918309.9903
        )

    [26] => Array
        (
            [0] => Array
                (
                    [cust_no] => 0
                    [creditcard_data] => Array
                        (
                            [fc] => module
                            [module] => billmatebank
                            [controller] => validation
                            [id_lang] => 1
                            [status] => 0
                            [currency] => SEK
                            [order_id] => 5-14219182
                            [error_message] => Approved
                            [amount] => 167842
                            [subscription_trans_id] => 0
                            [mac] => 659c49c4f54e92aae865bdad7af65bc52d9bff69aba3065ede2b51a90db5f3ef
                            [time] => 2015-01-22 10:18:29.446452
                            [test] => YES
                            [merchant_id] => 7270
                            [pay_method] => handelsbanken
                            [trans_id] => 800823210
                        )

                    [status] => Paid
                )

        )

)

**Comment by Boxedsolutions** [comment]
Will begin to work with this Issue. Its a compatibility Issue.

**Comment by Boxedsolutions** [comment]
Should work now. Will you verify @joakim-combain

**Comment by andyjohansson** [comment]
Don't forget to change assignee when it should be tested @Boxedsolutions :)

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
