### ISSUE TITLE
1.5 - There seems to be issues with rounding.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#45]
Check invoice 6556 and order id 12. It's 0.01 off from store. Please check if you can fix this somehow.

**Comment by Boxedsolutions** [comment]
Rounding? ;)

**Comment by andyjohansson** [comment]
Avrundning in Swedish

**Comment by Boxedsolutions** [comment]
Yes i Know English. But its one Solution.

**Comment by Boxedsolutions** [comment]
Its Prestashop that rounds thing in a strange way. A solution to this would be to add a rounding on the invoice.

**Comment by joakim-combain** [comment]
I tried to fix this with out other developer but he just said that it was impossible to do that for some reason. Would be great if you could find a way to send in an additional product. The old api doesn't work as great as the new one, unfortunately. :smile:

**Comment by andyjohansson** [comment]
We will skip this for now I think, the new one is just around the corner :)

**Comment by andyjohansson** [comment]
We wont fix this one, it will be fixed in the new API.
