### ISSUE TITLE
1.5 - When I use card, you set the invoice as paid, undepending on the transaction mode.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#46]
Both Sale and Authorization is setting the invoice as paid, however the amount is not debited in Authorization.

**Comment by andyjohansson** [comment]
So it's sending in the wrong flag?

**Comment by Boxedsolutions** [comment]
Should work now @joakim-combain

**Comment by joakim-combain** [comment]
This is fixed. Closing it.
