### ISSUE TITLE
1.5 - Bank is not translated in english. It's always in swedish.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#47]
You need to translate bank payment window. It works in our new api so it should work here as well.

Bank should be limited to swedish customers only, but we need to support english language.

**Comment by joakim-combain** [comment]
![web payment1](https://cloud.githubusercontent.com/assets/10434920/5854580/a73ccda0-a22f-11e4-8ee0-6351d6e59b65.png)

**Comment by Boxedsolutions** [comment]
Should work now. But Regarding to callback is processed in the same time as  accept url, i Will have to find a way around this.

**Comment by joakim-combain** [comment]
This is fixed from our side. The rest is d2i stuff, if you in bank payment window choose one bank and press pay, that page is still in swedish. Have e-mailed @andyjohansson about this issue. Should I close this since it's done from our side or should we wait until response from d2i?

**Comment by Boxedsolutions** [comment]
![banklanguage](https://cloud.githubusercontent.com/assets/8977650/5856819/d513e2e2-a246-11e4-886f-503b49105ad8.png)
It in english

**Comment by joakim-combain** [comment]
Yes, but not this page. 
![https cardpay billmate se pay bank testbank handelsbanken](https://cloud.githubusercontent.com/assets/10434920/5856892/5974c970-a247-11e4-92d9-f269196e4ae1.png)

**Comment by andyjohansson** [comment]
That one, we can't translate, it's out of our control. Will contact them about it. Can we close it otherwise?
