### ISSUE TITLE
1.5 - Swedish error message with english store setting.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#48]
The error messages in invoice and part pay are still in swedish even though the store is set to english language. Everything else is in english.

**Comment by joakim-combain** [comment]
![teststore](https://cloud.githubusercontent.com/assets/10434920/5854713/14eb5212-a231-11e4-8809-82377b5a74fd.png)

**Comment by Boxedsolutions** [comment]
These not so smart Translation principles in Prestashop makes things pretty interesting.

**Comment by Boxedsolutions** [comment]
Hmm this comes from The Api. 
How Should we solve it @andyjohansson

**Comment by andyjohansson** [comment]
We can't solve it I think, I don't think the old API is sending error messages in the correct language, right @joakim-combain? If not, we leave this for the new API and version 2.0.

**Comment by joakim-combain** [comment]
Hmm, not sure. I think it's up to you if you feel that it's important enough to put more time into, since we are releasing a new plugin that handels this a lot better. I'd assume the idea is for all of our customers to upgrade to the new plugin and not stay with these old ones?

**Comment by andyjohansson** [comment]
We leave this one for now. We will try to get everyone to update to the newest version when it's available.
