### ISSUE TITLE
See if we can remove the extra page where you enter the org. / pers. nr

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#49]
Have it on the same page as the checkout.

**Comment by Boxedsolutions** [comment]
Could you verify this

**Comment by joakim-combain** [comment]
This is fixed, but the payment options looks really bad and needs to be fixed. Related to #126.

**Comment by Boxedsolutions** [comment]
Should be better styled now

**Comment by joakim-combain** [comment]
Commented on this issue in #126.

**Comment by joakim-combain** [comment]
Commented on this issue in #126 but closing this issue since we don't need two of them.
