### ISSUE TITLE
Settings window for card is going outside the margins.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#50]
![prestashop administration panel](https://cloud.githubusercontent.com/assets/10434920/5871764/780b320c-a2e2-11e4-87bc-fb512841391d.png)

As you can see "Reservera belopp (debitera i billmate online)" makes it go outside. My question is if this is something we need to even bother with or if we should fix it?

**Comment by joakim-combain** [comment]
Actually, all of them seem to do this.
![prestashop administration panel2](https://cloud.githubusercontent.com/assets/10434920/5871775/cdd5bafe-a2e2-11e4-986c-ef778b755c46.png)

**Comment by andyjohansson** [comment]
I think it's a quick CSS fix.

**Comment by Boxedsolutions** [comment]
Should be solved now

**Comment by andyjohansson** [comment]
@joakim-combain please test :+1:

**Comment by joakim-combain** [comment]
I found this. It's a quick issue to fix. When fixed we can close this issue.
![prestashop administration 4](https://cloud.githubusercontent.com/assets/10434920/5896441/dc5d7e86-a535-11e4-927e-3e9b1e655e4c.png)

**Comment by andyjohansson** [comment]
Will you take a look @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Should not be so messy now.

**Comment by joakim-combain** [comment]
Looks good now. Closing the issue.
