### ISSUE TITLE
I get HTTP error when I try to access bank and when I try to complete a card payment.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#51]
![http error](https://cloud.githubusercontent.com/assets/10434920/5871875/514e576e-a2e4-11e4-859e-a20ada4302e8.png)

**Comment by Boxedsolutions** [comment]
Should work now

**Comment by joakim-combain** [comment]
It is still giving me HTTP error. :worried:

**Comment by Boxedsolutions** [comment]
Found the same compatibility Issue for 1.4. Should work now

**Comment by joakim-combain** [comment]
This issue is fixed. Closing the ticket.
