### ISSUE TITLE
I get fatal error when trying to access invoice payment method in checkout.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#52]
![teststore2](https://cloud.githubusercontent.com/assets/10434920/5871886/7a4cf332-a2e4-11e4-9739-438407703d52.png)

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
Now I get syntaxerror in Invoice, like I did with part pay. Probably same issue.

**Comment by Boxedsolutions** [comment]
I tested with:
 	MacBook 	1 463,21 kr 	1 	1 463,21 kr
  	iPod touch - Disk space : 8Go 	302,05 kr 	1 	302,05 kr
And discount teståäö. 

Do you have some other article?

**Comment by joakim-combain** [comment]
Those are the items I use as well. Could it be caching issue? Sounds weird though.

**Comment by andyjohansson** [comment]
Have you tried in a incognito window?

**Comment by joakim-combain** [comment]
No, will try that now.

**Comment by joakim-combain** [comment]
I get same issue in incognito window.

**Comment by andyjohansson** [comment]
Checkout as guest or as a registered user?

**Comment by joakim-combain** [comment]
I'm using a registered user. Don't really see how it would affect, but we've encountered stranger stuff.

**Comment by Boxedsolutions** [comment]
I checked out as guest. But I will test as registered user.

**Comment by Boxedsolutions** [comment]
I cant reproduce :(

**Comment by joakim-combain** [comment]
What browser are you using?

**Comment by joakim-combain** [comment]
I'm using åäö in all my fields. Try logging in with my account and see if you can reproduce it.

USer: joakim@efinance.se
Pass: Hej123

**Comment by joakim-combain** [comment]
Nevermind. It works now... Strange....

**Comment by Boxedsolutions** [comment]
I have to say its very strange that errors solve itselfs.

**Comment by andyjohansson** [comment]
We keep this one open for a while...

**Comment by joakim-combain** [comment]
Hmm... I'll keep an eye out and see if I encounter it again. Mostliley something saved in some session or something... Strange thought that it didn't work in incognito.... Anyway, I'll run my tests and see if I encounter it again.

**Comment by joakim-combain** [comment]
I got the syntax error again. I used 5505050558 to generate the error message.

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
This is fixed. Closing the issue.
