### ISSUE TITLE
I get syntaxerror in console when trying to check out with part payment.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#53]
![syntaxerror prestashop](https://cloud.githubusercontent.com/assets/10434920/5871918/d42bf718-a2e4-11e4-9afe-e3292ae8db76.png)

**Comment by Boxedsolutions** [comment]
Should work now

**Comment by joakim-combain** [comment]
Still giving me syntaxerror. I've cleared the cache so this shouldn't be a problem. :worried:

**Comment by Boxedsolutions** [comment]
What articles do you have in cart? I need to reproduce to solve it. 

For me it working with one article.

**Comment by joakim-combain** [comment]
1 x MacBook
1 x iPod touch
Discount code: teståäö

**Comment by Boxedsolutions** [comment]
Found the problem. A compatibility Issue for 1.4, when discount was added. Should work now

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
