### ISSUE TITLE
This error message is wrong encoded in invoice and part pay

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#54]
![wrong encoding prestashop](https://cloud.githubusercontent.com/assets/10434920/5874372/eeaa616c-a300-11e4-86f4-ad170b50d18a.png)

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
I get this issue now when trying to checkout with invoice...
![personnummer saknas](https://cloud.githubusercontent.com/assets/10434920/5915741/a53d1cb6-a609-11e4-8eef-60a50473fd4e.png)

**Comment by Boxedsolutions** [comment]
Its fixed now.

**Comment by joakim-combain** [comment]
![teststore4](https://cloud.githubusercontent.com/assets/10434920/5915913/7754867a-a60b-11e4-9898-512b0f59dfdf.png)

You need to put a space here in the error message. Should be same for part pay as well.

**Comment by Boxedsolutions** [comment]
A space is added.

**Comment by joakim-combain** [comment]
this issue is fixed. Closing it.
