### ISSUE TITLE
When I press "Andra betalningsmetoder" in Invoice I get this page.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#57]
![prestaold14 boxedtest se order step 3](https://cloud.githubusercontent.com/assets/10434920/5874470/1ef4b092-a302-11e4-9bc8-66e033d37bd7.png)

**Comment by Boxedsolutions** [comment]
I guess it will solve itself when we inactivate developer mode.

**Comment by andyjohansson** [comment]
It should still work in test mode?

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
