### ISSUE TITLE
I get wrong amounts in articles in our bo invoice.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#59]
Check Invoice 6635 and ordernumber in store #000025.

**Comment by Boxedsolutions** [comment]
Its a Prestashop Issue. The prices is saved  with many decimals in Database 1170.568561. But we are only getting 2 decimals from Cart. My idea is that is why its failing. I will think about a solution.

**Comment by andyjohansson** [comment]
This should be resolved in 2.0 update?

**Comment by Boxedsolutions** [comment]
Yes we apply rounding. The amount of rounding may vary alot if we not come up with a supersmart strategy for getting correct prices as Prestashop seems to not handle it correctly

**Comment by andyjohansson** [comment]
Can you test this @joakim-combain?

**Comment by joakim-combain** [comment]
I will check this after lunch.

**Comment by Boxedsolutions** [comment]
Yes, it is. 
It calculates the amounts in the same way for all payment methods.. So if one is correct, the other should be. But it might be an idea to test one order with all methods just to verify.

**Comment by andyjohansson** [comment]
Is it implemented on all the test stores?

**Comment by Boxedsolutions** [comment]
Yes it is.

**Comment by joakim-combain** [comment]
I checked 1.5 and the pdf in Billmate Online is wrong by 0.01. This is due to you sending in 3 decimals and then we round it to 2 decimals in pdf. Is it possible for you to just send in 2 decimals or does this mess your fix up?

**Comment by Boxedsolutions** [comment]
Will check that.

**Comment by joakim-combain** [comment]
Invoice number 6682 and order reference OEVQMJTKP

**Comment by Boxedsolutions** [comment]
Its a Prestashop feature, that makes this. It would be solved with the new Api. As prestashop only gives a rounded price with 2 decimals for the cart products but calculates itself with 4 decimals.

**Comment by andyjohansson** [comment]
So we leave this one for the new API?

**Comment by Boxedsolutions** [comment]
Yes, its my suggest. As we use the rounding for the tiny differences.

**Comment by joakim-combain** [comment]
That's fine by me. Should we close this issue then?

**Comment by andyjohansson** [comment]
I will change this one to the new API version 2.0 so we won´t forget to cross check it.
