### ISSUE TITLE
Automatically update PClasses

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#6]
Write a function that automatically updates all the PClasses, once a week.

**Comment by Boxedsolutions** [comment]
Implemented the logic for checking if any pclass has expired and updates this

**Comment by victorauren** [comment]
Is there a static time this function runs on? @Boxedsolutions

**Comment by Boxedsolutions** [comment]
No its runs a check every time the plans is fetched from database if some is expired, fetch the new ones.

**Comment by victorauren** [comment]
Works fine
Closing issue
