### ISSUE TITLE
The store is counting vat twice for shipping.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#60]
![5](https://cloud.githubusercontent.com/assets/10434920/5875313/17f90202-a30c-11e4-8714-36b43c0bc888.png)
![order teststore5](https://cloud.githubusercontent.com/assets/10434920/5875314/17fc4f84-a30c-11e4-8df1-1ad6ea347044.png)

10 x 1.25 = 12.5 but it's showing 15.00. Not sure that this is a plugin issue, could just be prestashop issue, but we have seen previously that our plugins could affect these things. Could be good to atleast take a look so they don't.

**Comment by Boxedsolutions** [comment]
Its correct. If you check Hantering, there is 2kr and Hantering incl Vat is 2.50 + 12.50 = 15

**Comment by andyjohansson** [comment]
Please verify @joakim-combain.

**Comment by joakim-combain** [comment]
Ah. Yeah, it's correct. I didn't see that. Closing the issue.
