### ISSUE TITLE
Shipping is wrong in our BO invoices.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#61]
Should have been 22.40 but it's 22.00 in our invoice. Not sure if this is related with the other issue with amounts.

See invoice 6636 and order id 000026.

**Comment by Boxedsolutions** [comment]
@joakim-combain  Did you found any more Shipping Fee errors?

**Comment by andyjohansson** [comment]
@joakim-combain did you find any more shipping Fee errors, can you test again?

**Comment by joakim-combain** [comment]
No, it was just that one and when I check it I can't see any further issues with shipping.

**Comment by andyjohansson** [comment]
Ok, if it´s still an issue the final tests will reveal it.
Closing.
