### ISSUE TITLE
Popup in invoice and part pay is not translated.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#64]
![teststore6](https://cloud.githubusercontent.com/assets/10434920/5876264/2e7399fc-a316-11e4-8e6a-1e540cad06b6.png)
![teststore7](https://cloud.githubusercontent.com/assets/10434920/5876265/2e912026-a316-11e4-9188-3a25fd18e5d1.png)

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
