### ISSUE TITLE
Uninstall issues

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#65]
Clients have reported uninstall errors on the Billmate Modules. Can you test this @joakim-combain?

**Comment by joakim-combain** [comment]
I have no problems either uninstalling or installing. Are they talking about removing it all together or just uninstalling it?

**Comment by andyjohansson** [comment]
Uninstalling. I have asked for more details, the exact words from the client are:
"Dessutom får jag bara massa felmeddelande, får rensa cache i shoppen och ha mig om man avinstallerar en billmatemodul."

**Comment by joakim-combain** [comment]
These are no issues I've encountered. I can't see any issues with it. Must be something else on their side. Maybe some plugin colliding with ours?

**Comment by andyjohansson** [comment]
Awaiting response from client.

**Comment by andyjohansson** [comment]
Still having issues, I´ve told them to update to 1.35.1 now. Let´s wait for their response.
