### ISSUE TITLE
Change "per månad" to "/ månad"

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#67]
![skarmavbild 2015-01-27 kl 10 37 50](https://cloud.githubusercontent.com/assets/4968755/5916362/9d63e964-a610-11e4-8897-985a844843a8.png)

**Comment by Boxedsolutions** [comment]
This is not translated to "/ månad",  Will do after the test

**Comment by Boxedsolutions** [comment]
This is translated in the latest commit

**Comment by joakim-combain** [comment]
I'll post this here as well.

/ månad is not translated in checkout page. This is only for 1.4.

![order teststore1](https://cloud.githubusercontent.com/assets/10434920/5934248/eb2038a8-a6cc-11e4-916f-e7a8fa0a6de1.png)

**Comment by Boxedsolutions** [comment]
Should be fixed.
