### ISSUE TITLE
Change terms & conditions text

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#68]
Change the text
"Jag godkänner även köpvillkor för faktura betalning"
to
"Jag godkänner även köpvillkoren för faktura betalning" (And link köpvillkoren to the terms & conditions lightbox)
![skarmavbild 2015-01-27 kl 10 39 30](https://cloud.githubusercontent.com/assets/4968755/5916383/d10af3a2-a610-11e4-976f-ab85dbba53f3.png)

**Comment by Boxedsolutions** [comment]
Should the whole sentence be Linked?

**Comment by andyjohansson** [comment]
No, just "Köpvillkoren".

**Comment by andyjohansson** [comment]
And apply the same thing to part payment option.

**Comment by joakim-combain** [comment]
The whole sentence is linked, not just "köpvilloren". Same for invoice as well.

![teststore11](https://cloud.githubusercontent.com/assets/10434920/5919297/d6141276-a632-11e4-989e-3f505ab691df.png)

**Comment by andyjohansson** [comment]
We changed this to the whole sentence.

**Comment by joakim-combain** [comment]
Then it's fixed.
