### ISSUE TITLE
Titles of the pages when you checkout

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#69]
We need to make sure that we have good looking page titles <title>. Totday it´s only the stores name. If we can change these.

**Comment by Boxedsolutions** [comment]
If we make success with #49 Then I guess this issue is not needed?

**Comment by andyjohansson** [comment]
Exactly, closing this one since I know we are on the path to this in the new one.

**Comment by andyjohansson** [comment]
But wait, we need this on bank & card @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Why its only to redirect the user to the paymentGateway

**Comment by andyjohansson** [comment]
Do we need the extra page? Can't the redirect be made directly?

**Comment by Boxedsolutions** [comment]
Its so it is implemented now in api 2.0. I cant see any use of a extra page

**Comment by andyjohansson** [comment]
Super, closing.
