### ISSUE TITLE
Visually & translation changes to the invoice & part payment pages

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#70]
See this image. Get in touch if more clarification is needed.
![prestashop_checkout_changes](https://cloud.githubusercontent.com/assets/4968755/5916967/e516a056-a617-11e4-896c-ece2504263a0.png)

**Comment by joakim-combain** [comment]
Is this issue only in 1.6 or is it fixed for all?

**Comment by andyjohansson** [comment]
@Boxedsolutions should have taken all of these and implemented them across 1.4, 1.5 & 1.6.
Let us know if you find anything that looks off.

**Comment by joakim-combain** [comment]
![teststore12](https://cloud.githubusercontent.com/assets/10434920/5919631/f5f3705c-a635-11e4-815e-277c8b75c63b.png)
![teststore13](https://cloud.githubusercontent.com/assets/10434920/5919632/f5f95e7c-a635-11e4-968d-bb374e7f82cb.png)

This is 1.4.

**Comment by joakim-combain** [comment]
![teststore14](https://cloud.githubusercontent.com/assets/10434920/5919805/89290188-a637-11e4-9a9f-0235bc3bc7bf.png)
![teststore15](https://cloud.githubusercontent.com/assets/10434920/5919806/8948e110-a637-11e4-9c0f-8e6d64e37e8c.png)

1.5

**Comment by andyjohansson** [comment]
Remove "dej" also.

**Comment by joakim-combain** [comment]
![teststore16](https://cloud.githubusercontent.com/assets/10434920/5920209/ffe9cdb8-a63a-11e4-8f4b-02a4865dc7e6.png)
![teststore17](https://cloud.githubusercontent.com/assets/10434920/5920210/ffec9552-a63a-11e4-8345-49c1e9d5379c.png)

1.6

**Comment by Boxedsolutions** [comment]
Fixed but need to find out #75

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
I found this. Should be quick to fix it.

![order teststore1](https://cloud.githubusercontent.com/assets/10434920/5933995/ee3f6a80-a6c8-11e4-980f-9358df96ac2e.png)

**Comment by Boxedsolutions** [comment]
Should be fixed
