### ISSUE TITLE
Is it possible to get rid of this billmate invoice fee?

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#73]
This happens if you order with invoice and then reorders the order.
![order teststore6](https://cloud.githubusercontent.com/assets/10434920/5918613/e4e91db2-a62a-11e4-9689-f120ec121ab6.png)

**Comment by andyjohansson** [comment]
It will be possible when we use a new implementation for this. It will be resolved in version 2.0, right @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
It might be possible if we hook into actionCartSave and check if billmateInvoice id is in cart and if it is remove it?

**Comment by joakim-combain** [comment]
It's worth a try? Worst case it doesn't work?

**Comment by andyjohansson** [comment]
If so it should be removed completly from the cart and just be added when you select the payment type on invoice. Is it possible @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
But according to the code it should not be possible to add it twice. I will check for a solution.

**Comment by joakim-combain** [comment]
It doesn't add it double. I think it's removed when you choose a payment method. But it's put in if you use the prestashop function to reorder. So it is only visible in the cart, but could be confusing for the customers.

**Comment by andyjohansson** [comment]
We will leave this one for now and fix it in 2.0 release with a new implementation.

**Comment by andyjohansson** [comment]
How are the thoughts going about this one @Boxedsolutions ?

**Comment by Boxedsolutions** [comment]
Could you verify this?

**Comment by joakim-combain** [comment]
This issue is not relevant anymore. Closing it.
