### ISSUE TITLE
In part pay there are different values shown in the store compared what is in BO. Is this something we need to care about?

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#74]
![teststore10](https://cloud.githubusercontent.com/assets/10434920/5919215/06047fa8-a632-11e4-9f5c-e3af2787d017.png)
![ordrar fakturor billmate](https://cloud.githubusercontent.com/assets/10434920/5919216/060dd08a-a632-11e4-97ca-079c95ccf092.png)

Vi verkar avrunda när vi visar i BO, men kanske inget vi bryr oss om att ändra?

**Comment by Boxedsolutions** [comment]
its just about rounding. It would be an easy fix.

**Comment by andyjohansson** [comment]
We should always round up to the closest whole number then.

**Comment by Boxedsolutions** [comment]
This is fixed

**Comment by joakim-combain** [comment]
Is it possible to remove the decimals? Looks weird to have them when it's just ,00.

![teststore19](https://cloud.githubusercontent.com/assets/10434920/5934020/5cd2dd42-a6c9-11e4-9378-30c401bfacc6.png)

**Comment by Boxedsolutions** [comment]
Solved. Should work on all versions
