### ISSUE TITLE
Are we ok with row breaking in the invoice module on the checkout page?

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#76]
![order teststore20](https://cloud.githubusercontent.com/assets/10434920/5934355/7da4ed94-a6ce-11e4-95a6-af11efa21a06.png)

Are we ok with this or should we fix it? I think it looks kind of bad.

**Comment by andyjohansson** [comment]
We should fix this so that it´s only new row, i think this is possible if we float the elements @Boxedsolutions.

**Comment by Boxedsolutions** [comment]
If we float the elements, the centering would be  messed up.

**Comment by andyjohansson** [comment]
Can you come up with another solution, I know that I have come up with solutions like that before :+1:

**Comment by Boxedsolutions** [comment]
Will find something. :)

**Comment by Boxedsolutions** [comment]
What browser is it? I tried to minimize my window and its not breaking row ever. I'm using Chrome
![fakturabetalningssatt](https://cloud.githubusercontent.com/assets/8977650/5936445/01f2cd9e-a6e5-11e4-8023-f542a6655ed1.png)

**Comment by andyjohansson** [comment]
Looks good on my Safari, Chrome & IE.
![skarmavbild 2015-01-28 kl 12 01 51](https://cloud.githubusercontent.com/assets/4968755/5936527/c55bbc64-a6e5-11e4-8361-f80905702af9.png)
![skarmavbild 2015-01-28 kl 12 03 51](https://cloud.githubusercontent.com/assets/4968755/5936528/c56004c2-a6e5-11e4-838b-fa51a04f04ed.png)
![skarmavbild 2015-01-28 kl 12 03 12](https://cloud.githubusercontent.com/assets/4968755/5936529/c56114ca-a6e5-11e4-8da4-f7ee7180df95.png)

**Comment by andyjohansson** [comment]
Issue exist on Chrome Windows, resolution 1024x768 (Running a VM) also tried 1920x1080 so error seems to exist only on windows Chrome.
Trying to solve it...
![skarmavbild 2015-01-28 kl 13 55 12](https://cloud.githubusercontent.com/assets/4968755/5937886/6a1e14ea-a6f5-11e4-9fa3-40392a1f9e7b.png)

**Comment by Boxedsolutions** [comment]
Added The fix for this.

**Comment by andyjohansson** [comment]
This aren't possible to fix. We will reformulate the sentence on 1.4 to be displayed correctly in the not-so-wide sh***y design :+1:
