### ISSUE TITLE
Add hover text-decoration underline to "Andra betaningsmetoder" & "Villkor för delbetalning"

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#78]
![skarmavbild 2015-01-28 kl 15 05 37](https://cloud.githubusercontent.com/assets/4968755/5938936/bf2dfe14-a6ff-11e4-9f84-941b1952e774.png)

**Comment by andyjohansson** [comment]
Not fixed?

**Comment by Boxedsolutions** [comment]
Should be

**Comment by andyjohansson** [comment]
No, it´s not fixed, tried on three different browsers with clean cache.

**Comment by andyjohansson** [comment]
Look at the 1.6, on the other one's it works.

**Comment by Boxedsolutions** [comment]
Should be now.

**Comment by andyjohansson** [comment]
I think there must be a missunderstanding now, the underline should only be visible on hover.

**Comment by Boxedsolutions** [comment]
Yes but now its fixed

**Comment by andyjohansson** [comment]
Should be fixed by b027f8abb54b3c1a9142c1a243b4e7f4b6bc1964
