### ISSUE TITLE
Update everwhere eFinance Nordic AB is named

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#8]
Update to the new company name Billmate AB.

**Comment by andyjohansson** [comment]
Check Billmate.php
Check billmateCart.php
Check preOrder.php

**Comment by Boxedsolutions** [comment]
Will you check? @andyjohansson

**Comment by andyjohansson** [comment]
Check row 10 in billmate.php change to billmate.se and then you can close.
