### ISSUE TITLE
The checkbox is placed on the wrong level

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#81]
Part payment & Invoice.
![skarmavbild 2015-01-28 kl 15 32 53](https://cloud.githubusercontent.com/assets/4968755/5939337/195d420c-a703-11e4-91cc-59b8ef84bcb0.png)
![skarmavbild 2015-01-28 kl 15 33 37](https://cloud.githubusercontent.com/assets/4968755/5939338/195ecd5c-a703-11e4-8eeb-352999e026d8.png)

**Comment by Boxedsolutions** [comment]
Should be fixed now
