### ISSUE TITLE
Different styles on the submit buttons

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#82]
Use the big one.
![skarmavbild 2015-01-28 kl 15 32 53](https://cloud.githubusercontent.com/assets/4968755/5939345/2949c988-a703-11e4-899d-97a349743f27.png)
![skarmavbild 2015-01-28 kl 15 33 37](https://cloud.githubusercontent.com/assets/4968755/5939346/294cb5ee-a703-11e4-99c6-214203140725.png)

**Comment by andyjohansson** [comment]
The same applies to 1.5 as 1.6

**Comment by Boxedsolutions** [comment]
Shoud be fixed in latest commit

**Comment by andyjohansson** [comment]
Looks correct.
