### ISSUE TITLE
Does part payment options display on front end if the PClass are outdated?

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#83]

**Comment by Boxedsolutions** [comment]
Yes it does. Its no check agains the expire date. Maybe we add in future hotfix?

**Comment by andyjohansson** [comment]
This will be fixed in the 2.0 release then.

**Comment by joakim-combain** [comment]
I try to change keys now but when I save it it reverts back to 7270 keys. I'm trying to change to this key: 9495 828885158288

This set of keys should have paymentplan that has expired.

**Comment by Boxedsolutions** [comment]
It should work. I changed the expirydate to 2015-02-21 for 3 months partpayment and this isnt visible on frontend

**Comment by joakim-combain** [comment]
I noticed that we load the standard pclasses as well as the specific pclasses. Is this how it should work? They are not visible in front end. Not sure if we have discussed this or if you have decided it should be like this?

**Comment by Boxedsolutions** [comment]
Yes I think so, if a plan is outdated we couldnt get it from the API as it restricts on the api side. We are fetching available pclasses.

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
