### ISSUE TITLE
Rewrite the autocapture (Card & Bank) for better handling order nr. between Prestashop and BO

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#85]
Autocapture should be false.
The flow should be the following:
* Autocapture false
* Update order no.
* Activate payment

**Comment by andyjohansson** [comment]
Could you test this @joakim-combain? We added sale / authorization settings for bank payments as well, so this needs to be tested.
Also, verify the auto capture flow for payments that have sale as the setting on card / bank payments.
The flow is described above.

**Comment by joakim-combain** [comment]
I just tested this and had settings in card to debit but the invoice was set as created instea of paid in BO.

See invoice 6767. this was in 1.4.

**Comment by joakim-combain** [comment]
I noticed something worse. When I have debit on it doesn't debit the card in d2i even.

**Comment by Boxedsolutions** [comment]
How does you see if its debited on d2i? Check invoice 6773, Its under paid invoices

**Comment by joakim-combain** [comment]
You can find it in api logs, I can find it in our database and check it. Andreas is able to chack it as well if you have the transaction id.

If you check 6767, 6768 and 6769 they all ended up in created but 6767 and 6769 should be in paid. I can try again...

**Comment by joakim-combain** [comment]
Hmm, seems like it works now... Were you working on it or something while I tested it? It's weird that it fixed itself just like that. It's debiting now as well... So Seems like it works on 1.4...

**Comment by Boxedsolutions** [comment]
I re uploaded my files if I might missed something to debug, why it wasnt work. And it seems to fixed it?

**Comment by joakim-combain** [comment]
Yeah, seems like it fixed it.

**Comment by joakim-combain** [comment]
Now 1.5 is putting all card as paid instead.... What's this? Do you need to upload it again? 6777, 6778 and 6779.

**Comment by Boxedsolutions** [comment]
I checked the database and its in sale mode. I will check if Change settings will change the value in the database.

**Comment by joakim-combain** [comment]
Ok. Because it seems like I have issues with bank now as well. I put two orders one debit and one reserve but both seems to have ended up in created in BO :/

**Comment by Boxedsolutions** [comment]
I just tested both bank and card with debit and they are under Paid. 

Just to verify, test to change payment mode and we will se if the database updates. Something is really wierd :(

**Comment by joakim-combain** [comment]
6784 is in paid but the bank setting is reserve amount :worried:

**Comment by Boxedsolutions** [comment]
Did you update the setting? Its not changed in the database :(

**Comment by joakim-combain** [comment]
I did update the settings.

![prestashop administration panel](https://cloud.githubusercontent.com/assets/10434920/5975377/6322d4dc-a880-11e4-9639-c49fdb8485ef.png)

**Comment by Boxedsolutions** [comment]
prestaold15.boxedtest.se/administration ? It seems like your changing 1.4?

**Comment by joakim-combain** [comment]
Ah... Shit... Sorry :fearful:

**Comment by joakim-combain** [comment]
I've checked them all and it seems to work very good. Closing the issue.

**Comment by andyjohansson** [comment]
Good!
