### ISSUE TITLE
Part pay from this amount in cart

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#86]
This would be a great new feature. To extend the cart to be able to display:
Part pay available from 350 SEK / month

**Comment by fermedia** [comment]
concur, this method works likes a charm in wordpress.
![image](https://cloud.githubusercontent.com/assets/11261123/6844128/98a4b45a-d3a9-11e4-90a3-42c176f4e007.png)

**Comment by Boxedsolutions** [comment]
Implemented on product page. Cart page is nearly impossible to use a hook for and would involve rewrite core to make possible.

**Comment by victorauren** [comment]
It shows on product that cost 100 and above, isn't the limit to use partpayment 200?

**Comment by Boxedsolutions** [comment]
check admin, its language dependent. In Enlish its 100

**Comment by victorauren** [comment]
It sure does. Works fine then

Closing issue
