### ISSUE TITLE
No order status is set if order status is not definied in backoffice

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#87]

**Comment by andyjohansson** [comment]
Also automatically select the correct order status in back-end if no order status is selected right now.

**Comment by Boxedsolutions** [comment]
Should be fixed now. If no status is set it Defaults to Prestashop standard Payment Accepted. And shows in Configuration payment accepted if no status isset.

**Comment by andyjohansson** [comment]
OK on 1.4
Will continue to test on 1.5 & 1.6

**Comment by andyjohansson** [comment]
Ok on 1.5

**Comment by andyjohansson** [comment]
OK on 1.6
