### ISSUE TITLE
Improve translation invoice & part payment

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#90]
This applies to all versions of the modules
* Personal Number --> Personal Number / Organization Number (Invoice & part payment)
* Please fill following fields for complete order --> Please fill the following fields to complete your order

**Comment by andyjohansson** [comment]
And it should be "(incl. tax)" instead for "(tax incl.)"

**Comment by Boxedsolutions** [comment]
It should be fixed

**Comment by andyjohansson** [comment]
Can we change back to (tax incl.)?

**Comment by Boxedsolutions** [comment]
Yes, its possible..

**Comment by andyjohansson** [comment]
Do that then ;)

**Comment by andyjohansson** [comment]
Inkluderar en fakturaavgiften på 19,90 kr (inkl. moms).
Includes an invoice fee of 19,90 kr (tax included).

This is for Billmate Invoice Checkout Window, see below.
![skarmavbild 2015-02-17 kl 17 50 10](https://cloud.githubusercontent.com/assets/4968755/6232602/71c459b0-b6cd-11e4-98db-1b47e3d656e5.png)
