### ISSUE TITLE
Is it wise to have AutoActivate as a dropdown menu to activate it?

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#93]
I'm thinking that it could be confusing for the customers. Wouldn't it be better to just have another set of radio buttons to activate AutoActivate? Just have them On / Off and then activate the drop down menu when it's set to On so the customer can choose the status of it.

Another idea would be to just use the order status that is already there, there aren't any special cases for when autoactivate is used or not. Either it's On or it's Off. It could really just be a big hassel for us to implement a new order status. The other idea would be to deactivate the order status option where you enter your keys and activate a new one when AutoActivate is ON. That way they could have different order statuses depending on if they want AutoActivate one day and the other day they want to turn it off for easy usage for the customer.

Thoughts?

**Comment by Boxedsolutions** [comment]
I think we have to have a dropdown with status that will trigger the activation of the invoice. As If a customer ships the order and set the activation status to Shipped. Then it will auto activate on given status. 

It might also be so that the customers have implemented som own statuses that they want to trigger activation on.

Its not a big work to add a radio button, I might took a shortcut when adding inactivated in the dropdown?

**Comment by andyjohansson** [comment]
To make it easier for clients to understand it I agree with you @joakim-combain. Could you make this change @Boxedsolutions?

We are not implementering extra order statuses, we are just hooking up to one that the store defines as the "shipped" status. So nothing extra is going on.

The client

**Comment by Boxedsolutions** [comment]
I will do it in a few minutes.

**Comment by andyjohansson** [comment]
Super!

**Comment by Boxedsolutions** [comment]
Now i have added radio buttons to activate and inactivate. When the client click on activate radiobutton i remove the disabled state on the dropdown. In commit 9ea471e

**Comment by andyjohansson** [comment]
Give it another go @joakim-combain.

**Comment by joakim-combain** [comment]
I found this issue. When I went to invoice settings in backend, the autoactivate function was inactivated but the drop down is active. If I change to activate and then inactivate it again, the drop down is inactivated.

![prestashop administration panel1](https://cloud.githubusercontent.com/assets/10434920/6102538/95600bb2-b038-11e4-9174-7b0da9d7ffe7.png)

**Comment by joakim-combain** [comment]
AutoActivate does not work in 1.4.

![autoactivate 3](https://cloud.githubusercontent.com/assets/10434920/6102644/93e1e9d4-b03a-11e4-8ab0-6861ded2a847.png)
![autoactivate 2](https://cloud.githubusercontent.com/assets/10434920/6102646/97ae9bb6-b03a-11e4-9241-4319ec2d7cc6.png)
![autoactivate 1](https://cloud.githubusercontent.com/assets/10434920/6102648/9afd3ca0-b03a-11e4-9483-9772b917697b.png)

**Comment by Boxedsolutions** [comment]
Yes 1.4 it is not possible right now to make auto aktivate.

**Comment by joakim-combain** [comment]
Can you remove it from that version then? doesn't make sense to have it there if it doesn't work.

**Comment by Boxedsolutions** [comment]
Yes sure. But it will take some time.

**Comment by joakim-combain** [comment]
Ok, then I think it's a priority issue, but it should definitley be fixed before we release it. @andyjohansson what do you think? It this high priority?

**Comment by Boxedsolutions** [comment]
We have to fix it before release. And I will do it now.

**Comment by joakim-combain** [comment]
I just tested 1.5 in incognito window and it doesn't work there either. Same issues as with 1.4.

**Comment by Boxedsolutions** [comment]
In 1.5 it should work. Wich payment method?

**Comment by joakim-combain** [comment]
Invoice. Didn't work in 1.6 either. I tested it in incognito so can't be a caching issue on my side.

**Comment by Boxedsolutions** [comment]
Ahh it can be that wee need to uninstall and install the modules in backend.

**Comment by joakim-combain** [comment]
Ok. I'll try it in 1.6.

**Comment by Boxedsolutions** [comment]
I cant really come up with another solution than reinstall the modules because of that i Hook into the actionOrderStatusUpdate hook.

**Comment by joakim-combain** [comment]
Nope, didn't work.

**Comment by Boxedsolutions** [comment]
I will check then. :)

**Comment by Boxedsolutions** [comment]
![bo](https://cloud.githubusercontent.com/assets/8977650/6103297/d1ae7554-b042-11e4-9fee-b4d401e5498d.png)

Invoice activated. As you have set Billmate Payment Accepted as status to activate on. You have to go to the order and update status to the set status. I did it this way because of if the Client set the status to Shipped and then update the order status to shipped as he would when he ships the order, then also the invoice is activated in BO.

**Comment by joakim-combain** [comment]
But won't AutoActivate give the impression that it will activate it directly? The customers might think this and never do anything to activate them and then there will be unactivated invocies in their BO accounts. Is this really the way it should work? @andyjohansson

**Comment by andyjohansson** [comment]
@Boxedsolutions will update the description and title.

**Comment by Boxedsolutions** [comment]
I am changing the translation right now. To make it more clear.

**Comment by andyjohansson** [comment]
This is pushed now to the servers as well @Boxedsolutions? Can @joakim-combain take it for a spin again?

**Comment by Boxedsolutions** [comment]
Yes It should be in commit ae308404490ef801146adb1a7819248eddc380b9

**Comment by joakim-combain** [comment]
Seems like it worked in 1.6 now but still no luck in 1.5.

**Comment by Boxedsolutions** [comment]
I reinstalled the modules. An tried to activate on status Shipped  and it seemed working with invoiceId 6956. I have set Status to activate to Shipped on all modules, but it doesnt matter which status to trigger.

We have to add to the documentation that our modules needs to be reinstalled to hook orderstatus change.

**Comment by joakim-combain** [comment]
Hmm, in card plugin we have autoactivate and sale/authorize settings. How should this work? Say if I have autoactivate and have sale as transaction method. How will this work out?

**Comment by Boxedsolutions** [comment]
It doesnt autoactivate if the setting is Sale as the invoice already is activated

**Comment by joakim-combain** [comment]
Ok, so should you be able to have both settings for card? The only time it will work is if they have authorize. Should we skip autoactivate entierly for card?

**Comment by Boxedsolutions** [comment]
No as the customer may want to auto activate card orders with the setting authorize when the order is shipped, as I think of it.

**Comment by joakim-combain** [comment]
Hmm, but would they ever want to do that? I understand with Invoice and Part pay, but with card and bank it seems unnecessary to me. What do you say @andyjohansson?

**Comment by joakim-combain** [comment]
It seems to me that we have two functions that does pretty much the same thing.

**Comment by Boxedsolutions** [comment]
Its not the same thing. With autoactivate the invoice is created on the status that is set. For example Shipped. So the invoice is then activated when the shop has shipped the order. 

But the Sale setting does activate the invoice Instantly.

**Comment by joakim-combain** [comment]
To me it seems like it's just another step in this new function. Instead of Customer pays -> Payment is set to paid it's Customer pays -> Store owner changes order status -> payment is paid. Or am I missing something here?

**Comment by Boxedsolutions** [comment]
This is the same now. The status should be set to Paid. Just that the customer can choose to autoactivate on a status for example Shipped. 

So when the order gets the status shipped, the order is activated and the shop owner has no need to go to BO and manually activate the invoice.

**Comment by joakim-combain** [comment]
Ok, I understand. But why would they want to wait to debit the customers card until the product is shipped? I mean, sale in transaction mode activates it directly without the user having to go to their BO account. But if you really feel like there could be customers who wants to wait to debit the money ubtil they ship the product then I'm fine with it.
