### ISSUE TITLE
EUR as currency for the invoice fee

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#95]
If a customer checks out with EUR in the cart the invoice fee gets marked as EUR as well.

Any suggestions on how we can resolve this @Boxedsolutions & @joakim-combain?

**Comment by Boxedsolutions** [comment]
I think i have the solution. We just need to verify it works with all versions.

**Comment by Boxedsolutions** [comment]
Should be fixed.

**Comment by andyjohansson** [comment]
We should get the specific price before we auto convert.

**Comment by Boxedsolutions** [comment]
To do this. Prestashop complains about that the product should be in default category. I think the only way is to add a couple of fields in the settings, but it will be messy i think

**Comment by andyjohansson** [comment]
We still send the Invoice fee as SEK if the currency is SEK. It is displayed correctly on PS side though.
(
                    [qty] => 1
                    [goods] => Array
                        (
                            [artno] => 
                            [title] => Billmate fakturaavgift
                            [price] => 1520
                            [vat] => 25
                            [discount] => 0
                            [flags] => 16
                        )

                )
![skarmavbild 2015-03-03 kl 10 07 41](https://cloud.githubusercontent.com/assets/4968755/6459237/288c02dc-c18d-11e4-8f5f-569726db0312.png)

**Comment by Boxedsolutions** [comment]
Will look it up.
Shouldnt be to big thing to fix

**Comment by andyjohansson** [comment]
Works on 1.6, 1.5 and 1.4.
