### ISSUE TITLE
Issues with EUR as currency then being converted to SEK

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#97]

**Comment by andyjohansson** [comment]
This is included now @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
I have tried both Invoice and card With euro, the only thing is that 0.01 rounding error. But the currency seems correct

**Comment by andyjohansson** [comment]
Is related with #95

**Comment by andyjohansson** [comment]
Works as much as it should work on 1.4, 1.5 & 1.6.
