### ISSUE TITLE
Version control in database

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#98]

**Comment by Boxedsolutions** [comment]
As it is now we store the version in database. I will implement a "migration_table" in Version 2.1 if there are som settings that needed to be updated. So that we only need to run necessary files when we run our updates.

**Comment by Boxedsolutions** [comment]
I added a field in the settings table to hold the installed files. For now its enough with files sorted alpabetically. F.ex Alpha, Beta. Then the plugin will now in which order to update the database

**Comment by andyjohansson** [comment]
Like!

**Comment by Boxedsolutions** [comment]
Should be implemented, hard to test. As it is no database updates for this version.

**Comment by Boxedsolutions** [comment]
closing, verified in database.
